// Generated by GitHub Copilot
import { CrimsonPro_400Regular, CrimsonPro_600SemiBold } from '@expo-google-fonts/crimson-pro';
import { Inter_500Medium } from '@expo-google-fonts/inter';
import { JetBrainsMono_500Medium } from '@expo-google-fonts/jetbrains-mono';
import { SpaceGrotesk_500Medium } from '@expo-google-fonts/space-grotesk';
import { useFonts } from 'expo-font';
import React from 'react';
import { ActivityIndicator, StyleSheet, View } from 'react-native';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { AppNavigator } from './src/navigation/AppNavigator';
import { AppProvider, useAppContext } from './src/state/AppContext';
import { AppThemeProvider } from './src/theme/ThemeProvider';

/** Render the themed application once fonts and persisted state are ready. */
function AppBootstrap() {
  const { loading, settings } = useAppContext();
  const [fontsLoaded] = useFonts({
    Inter_500Medium,
    SpaceGrotesk_500Medium,
    CrimsonPro_400Regular,
    CrimsonPro_600SemiBold,
    JetBrainsMono_500Medium,
  });

  return (
    <AppThemeProvider preference={settings.themePreference}>
      {loading || !fontsLoaded ? (
        <View style={styles.loadingState}>
          <ActivityIndicator size="large" color="#0A7B82" />
        </View>
      ) : (
        <AppNavigator />
      )}
    </AppThemeProvider>
  );
}

/** Mount the app providers needed for gestures, safe areas, state, and navigation. */
export default function App() {
  return (
    <GestureHandlerRootView style={styles.root}>
      <SafeAreaProvider>
        <AppProvider>
          <AppBootstrap />
        </AppProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  loadingState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FBFB',
  },
});
