// Generated by GitHub Copilot
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { MarkdownContent } from '../components/MarkdownContent';
import { useAppContext } from '../state/AppContext';
import { useThemeController } from '../theme/ThemeProvider';
import { fontFamilies, spacing } from '../theme/tokens';
import { RootStackParamList } from '../types';

type EditorScreenProps = NativeStackScreenProps<RootStackParamList, 'Editor'>;

const shortcuts = ['# ', '## ', '- ', '**bold**', '`code`', '[link](https://example.com)'];

/** Render a markdown editor with autosave and a live preview tab. */
export function EditorScreen({ navigation, route }: EditorScreenProps) {
  const { documents, saveDocument, settings } = useAppContext();
  const { tokens } = useThemeController();
  const document = useMemo(() => documents.find((item) => item.id === route.params.documentId), [documents, route.params.documentId]);
  const estimatedReadMinutes = useMemo(() => Math.max(1, Math.round((document?.wordCount ?? 0) / 220)), [document?.wordCount]);
  const [content, setContent] = useState(document?.content ?? '');
  const [lastSavedContent, setLastSavedContent] = useState(document?.content ?? '');
  const [activeTab, setActiveTab] = useState<'edit' | 'preview'>('edit');

  useEffect(() => {
    setContent(document?.content ?? '');
    setLastSavedContent(document?.content ?? '');
  }, [document?.content]);

  useEffect(() => {
    if (!document || content === lastSavedContent) {
      return;
    }

    const timeout = setTimeout(() => {
      void saveDocument(document.id, content);
      setLastSavedContent(content);
    }, 500);

    return () => {
      clearTimeout(timeout);
    };
  }, [content, document, lastSavedContent, saveDocument]);

  useEffect(() => {
    const unsubscribe = navigation.addListener('beforeRemove', (event) => {
      if (content === lastSavedContent) {
        return;
      }

      event.preventDefault();
      Alert.alert('Leave editor?', 'Recent edits are still being saved.', [
        { text: 'Stay', style: 'cancel' },
        {
          text: 'Leave',
          style: 'destructive',
          onPress: () => navigation.dispatch(event.data.action),
        },
      ]);
    });

    return unsubscribe;
  }, [content, lastSavedContent, navigation]);

  if (!document) {
    return (
      <View style={[styles.container, { backgroundColor: tokens.background, justifyContent: 'center', alignItems: 'center' }]}> 
        <Text style={[styles.muted, { color: tokens.textSecondary }]}>The selected document could not be found.</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, { backgroundColor: tokens.background }]}> 
      <View style={[styles.topCard, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
        <Text style={[styles.eyebrow, { color: tokens.secondary }]}>STUDIO MODE</Text>
        <Text style={[styles.title, { color: tokens.textPrimary }]}>{document.title}</Text>
        <Text style={[styles.subtitle, { color: tokens.textSecondary }]}>Shape the markdown, review the rendered result, and keep the editing tools close without overwhelming the page.</Text>

        <View style={styles.metaRow}>
          <View style={[styles.metaChip, { backgroundColor: tokens.surfaceMuted }]}>
            <Text style={[styles.metaChipLabel, { color: tokens.textPrimary }]}>{document.wordCount} words</Text>
          </View>
          <View style={[styles.metaChip, { backgroundColor: tokens.surfaceMuted }]}>
            <Text style={[styles.metaChipLabel, { color: tokens.textPrimary }]}>{estimatedReadMinutes} min read</Text>
          </View>
          <View style={[styles.metaChip, { backgroundColor: tokens.surfaceMuted }]}>
            <Text style={[styles.metaChipLabel, { color: tokens.textPrimary }]}>{content === lastSavedContent ? 'Saved' : 'Syncing'}</Text>
          </View>
        </View>

        <View style={[styles.segmentRow, { backgroundColor: tokens.surfaceMuted }]}> 
          <Pressable
            onPress={() => setActiveTab('edit')}
            style={[styles.segment, { backgroundColor: activeTab === 'edit' ? tokens.accent : 'transparent' }]}
          >
            <Text style={[styles.segmentLabel, { color: activeTab === 'edit' ? '#FFFFFF' : tokens.textPrimary }]}>Edit</Text>
          </Pressable>
          <Pressable
            onPress={() => setActiveTab('preview')}
            style={[styles.segment, { backgroundColor: activeTab === 'preview' ? tokens.accent : 'transparent' }]}
          >
            <Text style={[styles.segmentLabel, { color: activeTab === 'preview' ? '#FFFFFF' : tokens.textPrimary }]}>Preview</Text>
          </Pressable>
        </View>
      </View>

      <View style={styles.composerSection}>
        <View style={styles.sectionHeadingRow}>
          <Text style={[styles.sectionTitle, { color: tokens.textPrimary }]}>Quick inserts</Text>
          <Text style={[styles.muted, { color: tokens.textMuted }]}>Tap to drop syntax into the draft</Text>
        </View>

        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.toolbarRow}>
          {shortcuts.map((shortcut) => (
            <Pressable
              key={shortcut}
              onPress={() => setContent((currentValue) => `${currentValue}${currentValue.endsWith('\n') || !currentValue ? '' : '\n'}${shortcut}`)}
              style={[styles.shortcutChip, { backgroundColor: tokens.surface, borderColor: tokens.outline }]}
            >
              <Text style={[styles.shortcutLabel, { color: tokens.textPrimary }]}>{shortcut}</Text>
            </Pressable>
          ))}
        </ScrollView>
      </View>

      {activeTab === 'edit' ? (
        <View style={[styles.editorSurface, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}> 
          <View style={styles.sectionHeadingRow}>
            <Text style={[styles.sectionTitle, { color: tokens.textPrimary }]}>Draft</Text>
            <Text style={[styles.muted, { color: tokens.textMuted }]}>{content.length} characters</Text>
          </View>
          <TextInput
            multiline
            onChangeText={setContent}
            placeholder="Write markdown..."
            placeholderTextColor={tokens.textMuted}
            style={[
              styles.editor,
              {
                backgroundColor: tokens.surfaceMuted,
                color: tokens.textPrimary,
                borderColor: tokens.outline,
                fontSize: 18 * settings.fontScale,
                lineHeight: 28 * settings.fontScale,
              },
            ]}
            textAlignVertical="top"
            value={content}
          />
        </View>
      ) : (
        <View style={[styles.previewSurface, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}> 
          <View style={styles.sectionHeadingRow}>
            <Text style={[styles.sectionTitle, { color: tokens.textPrimary }]}>Rendered preview</Text>
            <Text style={[styles.muted, { color: tokens.textMuted }]}>Matches the reader typography</Text>
          </View>
          <ScrollView contentContainerStyle={styles.previewWrap} showsVerticalScrollIndicator={false}>
            <MarkdownContent content={content} fontScale={settings.fontScale} tokens={tokens} />
          </ScrollView>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.md,
    gap: spacing.md,
  },
  topCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.lg,
    gap: spacing.md,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  eyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  title: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 26,
    lineHeight: 30,
  },
  subtitle: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
    lineHeight: 22,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  metaChip: {
    borderRadius: 999,
    minHeight: 34,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  metaChipLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    lineHeight: 16,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: 4,
    borderRadius: 999,
  },
  segment: {
    flex: 1,
    minHeight: 48,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  segmentLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  muted: {
    fontFamily: fontFamilies.ui,
    fontSize: 13,
  },
  composerSection: {
    gap: spacing.sm,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  sectionTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 18,
  },
  toolbarRow: {
    gap: spacing.sm,
    paddingLeft: 2,
    paddingRight: spacing.md,
  },
  shortcutChip: {
    minHeight: 44,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  shortcutLabel: {
    fontFamily: fontFamilies.code,
    fontSize: 13,
  },
  editorSurface: {
    flex: 1,
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.md,
    gap: spacing.md,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  editor: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    fontFamily: fontFamilies.code,
    minHeight: 320,
  },
  previewSurface: {
    flex: 1,
    borderRadius: 28,
    borderWidth: 1,
    paddingTop: spacing.md,
    gap: spacing.md,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  previewWrap: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
  },
});