// Generated by GitHub Copilot
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import React, { useMemo, useState } from 'react';
import {
  Alert,
  FlatList,
  Pressable,
  RefreshControl,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import Animated, { useAnimatedStyle, useSharedValue, withSpring } from 'react-native-reanimated';

import { FileTile } from '../components/FileTile';
import { useAppContext } from '../state/AppContext';
import { useThemeController } from '../theme/ThemeProvider';
import { fontFamilies, spacing } from '../theme/tokens';
import { RootStackParamList, ThemePreference } from '../types';

type LibraryNavigation = NativeStackNavigationProp<RootStackParamList, 'Library'>;

const themeOptions: ThemePreference[] = ['system', 'light', 'dark', 'amoled', 'sepia'];

/** Render the bookshelf, import actions, and theme controls for the local markdown library. */
export function LibraryScreen() {
  const navigation = useNavigation<LibraryNavigation>();
  const {
    documents,
    error,
    importDocument,
    loading,
    refreshLibrary,
    removeDocument,
    settings,
    setThemePreference,
    setViewMode,
    toggleFavorite,
    togglePin,
  } = useAppContext();
  const { tokens } = useThemeController();
  const [refreshing, setRefreshing] = useState(false);
  const fabScale = useSharedValue(1);

  const fabStyle = useAnimatedStyle(() => ({
    transform: [{ scale: fabScale.value }],
  }));

  const continueReading = useMemo(
    () => documents.filter((document) => document.progress > 0).slice(0, 4),
    [documents]
  );
  const pinnedCount = useMemo(() => documents.filter((document) => document.pinned).length, [documents]);
  const favoriteCount = useMemo(() => documents.filter((document) => document.favorite).length, [documents]);
  const totalWords = useMemo(
    () => documents.reduce((sum, document) => sum + Math.max(document.wordCount, 0), 0),
    [documents]
  );

  /** Reload the bookshelf content for pull-to-refresh. */
  async function handleRefresh() {
    setRefreshing(true);
    await refreshLibrary();
    setRefreshing(false);
  }

  /** Confirm destructive deletion before removing the markdown file from storage. */
  function confirmDelete(documentId: string, title: string) {
    Alert.alert('Delete document?', `Remove "${title}" from your local library?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: () => {
          void removeDocument(documentId);
        },
      },
    ]);
  }

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: tokens.background }]}>
      <View pointerEvents="none" style={styles.backdropLayer}>
        <View style={[styles.backdropOrb, styles.backdropOrbLeft, { backgroundColor: `${tokens.accent}18` }]} />
        <View style={[styles.backdropOrb, styles.backdropOrbRight, { backgroundColor: `${tokens.secondary}14` }]} />
        <View style={[styles.backdropPanel, { backgroundColor: `${tokens.surfaceMuted}C8` }]} />
      </View>

      <FlatList
        key={`library-${settings.viewMode}`}
        contentContainerStyle={styles.contentContainer}
        data={documents}
        keyExtractor={(item) => item.id}
        ListEmptyComponent={
          <View
            style={[
              styles.emptyState,
              { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow },
            ]}
          >
            <Text style={[styles.emptyEyebrow, { color: tokens.secondary }]}>STARTER SHELF</Text>
            <Text style={[styles.emptyTitle, { color: tokens.textPrimary }]}>Bring in your first markdown file.</Text>
            <Text style={[styles.emptyBody, { color: tokens.textSecondary }]}>The reader is tuned for long sessions, export-ready notes, and an offline collection that feels curated instead of improvised.</Text>
            <Pressable
              onPress={() => void importDocument()}
              style={[styles.importButton, { backgroundColor: tokens.accent, shadowColor: tokens.shadow }]}
            >
              <Text style={styles.importButtonLabel}>Import Markdown</Text>
            </Pressable>
          </View>
        }
        ListHeaderComponent={
          <View style={styles.headerWrap}>
            <View
              style={[
                styles.heroCard,
                { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow },
              ]}
            >
              <View style={[styles.heroAccent, { backgroundColor: tokens.secondary }]} />
              <Text style={[styles.eyebrow, { color: tokens.secondary }]}>EDITORIAL LIBRARY</Text>
              <Text style={[styles.title, { color: tokens.textPrimary }]}>Read like the app was made for the page.</Text>
              <Text style={[styles.subtitle, { color: tokens.textSecondary }]}>A calmer library, stronger hierarchy, and faster handoff between search, editing, and immersive reading.</Text>

              <View style={styles.heroActionRow}>
                <Pressable onPress={() => navigation.navigate('Search')} style={[styles.primaryAction, { backgroundColor: tokens.textPrimary }]}>
                  <Text style={[styles.primaryActionLabel, { color: tokens.background }]}>Open Search</Text>
                </Pressable>
                <Pressable
                  onPress={() => void importDocument()}
                  style={[styles.secondaryAction, { backgroundColor: tokens.surfaceMuted, borderColor: tokens.outline }]}
                >
                  <Text style={[styles.secondaryActionLabel, { color: tokens.textPrimary }]}>Import File</Text>
                </Pressable>
              </View>

              <View style={styles.metricRow}>
                <View style={[styles.metricCard, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.metricValue, { color: tokens.textPrimary }]}>{documents.length}</Text>
                  <Text style={[styles.metricLabel, { color: tokens.textMuted }]}>documents</Text>
                </View>
                <View style={[styles.metricCard, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.metricValue, { color: tokens.textPrimary }]}>{pinnedCount}</Text>
                  <Text style={[styles.metricLabel, { color: tokens.textMuted }]}>pinned</Text>
                </View>
                <View style={[styles.metricCard, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.metricValue, { color: tokens.textPrimary }]}>{Math.max(1, Math.round(totalWords / 250))}</Text>
                  <Text style={[styles.metricLabel, { color: tokens.textMuted }]}>reading hrs</Text>
                </View>
              </View>
            </View>

            <View
              style={[
                styles.controlDeck,
                { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow },
              ]}
            >
              <View style={styles.controlHeader}>
                <View style={styles.controlHeaderCopy}>
                  <Text style={[styles.controlTitle, { color: tokens.textPrimary }]}>Atmosphere</Text>
                  <Text style={[styles.controlCaption, { color: tokens.textSecondary }]}>Switch themes and shelf density without breaking your reading flow.</Text>
                </View>
                <Text style={[styles.controlBadge, { color: tokens.textMuted }]}>{favoriteCount} favorites</Text>
              </View>

              <ScrollView contentContainerStyle={styles.themeRow} horizontal showsHorizontalScrollIndicator={false}>
                {themeOptions.map((themeOption) => {
                  const isActive = settings.themePreference === themeOption;

                  return (
                    <Pressable
                      key={themeOption}
                      accessibilityRole="button"
                      onPress={() => void setThemePreference(themeOption)}
                      style={[
                        styles.themeChip,
                        {
                          backgroundColor: isActive ? tokens.textPrimary : tokens.surfaceMuted,
                          borderColor: isActive ? tokens.textPrimary : tokens.outline,
                        },
                      ]}
                    >
                      <Text style={[styles.themeChipLabel, { color: isActive ? tokens.background : tokens.textPrimary }]}>{themeOption}</Text>
                    </Pressable>
                  );
                })}
              </ScrollView>

              <View style={[styles.segmentRow, { backgroundColor: tokens.surfaceMuted, borderColor: tokens.outline }]}>
                <Pressable
                  accessibilityRole="button"
                  onPress={() => void setViewMode('grid')}
                  style={[styles.segment, { backgroundColor: settings.viewMode === 'grid' ? tokens.accent : 'transparent' }]}
                >
                  <Text style={[styles.segmentLabel, { color: settings.viewMode === 'grid' ? '#FFFFFF' : tokens.textPrimary }]}>Gallery</Text>
                </Pressable>
                <Pressable
                  accessibilityRole="button"
                  onPress={() => void setViewMode('list')}
                  style={[styles.segment, { backgroundColor: settings.viewMode === 'list' ? tokens.accent : 'transparent' }]}
                >
                  <Text style={[styles.segmentLabel, { color: settings.viewMode === 'list' ? '#FFFFFF' : tokens.textPrimary }]}>Editorial</Text>
                </Pressable>
              </View>
            </View>

            {continueReading.length ? (
              <View style={styles.continueSection}>
                <View style={styles.sectionHeadingRow}>
                  <Text style={[styles.sectionLabel, { color: tokens.textPrimary }]}>Continue Reading</Text>
                  <Text style={[styles.sectionMeta, { color: tokens.textMuted }]}>Resume where you dropped out</Text>
                </View>
                <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.continueRow}>
                  {continueReading.map((document, index) => (
                    <Pressable
                      key={document.id}
                      onPress={() => navigation.navigate('Reader', { documentId: document.id })}
                      style={[
                        styles.continueCard,
                        { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow },
                      ]}
                    >
                      <View
                        style={[
                          styles.continueTopBar,
                          { backgroundColor: index % 2 === 0 ? `${tokens.accent}18` : `${tokens.secondary}1C` },
                        ]}
                      />
                      <Text numberOfLines={2} style={[styles.continueTitle, { color: tokens.textPrimary }]}>
                        {document.title}
                      </Text>
                      <Text numberOfLines={3} style={[styles.continueSnippet, { color: tokens.textSecondary }]}>
                        {document.preview}
                      </Text>
                      <View style={styles.continueFooter}>
                        <Text style={[styles.continueMeta, { color: tokens.textMuted }]}>{Math.round(document.progress * 100)}% read</Text>
                        <Text style={[styles.continueMeta, { color: tokens.secondary }]}>{Math.max(1, Math.round(document.wordCount / 220))} min left</Text>
                      </View>
                    </Pressable>
                  ))}
                </ScrollView>
              </View>
            ) : null}

            <View style={styles.sectionHeadingRow}>
              <Text style={[styles.sectionLabel, { color: tokens.textPrimary }]}>Collection</Text>
              <Text style={[styles.sectionMeta, { color: tokens.textMuted }]}>{documents.length} titles ready offline</Text>
            </View>

            {error ? <Text style={[styles.errorText, { color: '#C95D5D' }]}>{error}</Text> : null}
            {loading ? <Text style={[styles.loadingText, { color: tokens.textMuted }]}>Refreshing your shelf...</Text> : null}
          </View>
        }
        numColumns={settings.viewMode === 'grid' ? 2 : 1}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={handleRefresh} tintColor={tokens.accent} />}
        renderItem={({ item, index }) => (
          <View
            style={[
              styles.tileWrap,
              settings.viewMode === 'grid' ? styles.gridWrap : styles.listWrap,
              settings.viewMode === 'grid' && index % 2 === 0 ? styles.leftTile : undefined,
              settings.viewMode === 'grid' && index % 2 === 1 ? styles.rightTile : undefined,
            ]}
          >
            <FileTile
              document={item}
              fontScale={settings.fontScale}
              onDelete={() => confirmDelete(item.id, item.title)}
              onEdit={() => navigation.navigate('Editor', { documentId: item.id })}
              onOpen={() => navigation.navigate('Reader', { documentId: item.id })}
              onToggleFavorite={() => void toggleFavorite(item.id)}
              onTogglePin={() => void togglePin(item.id)}
              tokens={tokens}
              viewMode={settings.viewMode}
            />
          </View>
        )}
      />

      <Animated.View style={[styles.fabWrap, fabStyle]}>
        <Pressable
          accessibilityRole="button"
          onPress={() => void importDocument()}
          onPressIn={() => {
            fabScale.value = withSpring(0.94);
          }}
          onPressOut={() => {
            fabScale.value = withSpring(1);
          }}
          style={[styles.fab, { backgroundColor: tokens.textPrimary, shadowColor: tokens.shadow }]}
        >
          <Text style={[styles.fabLabel, { color: tokens.background }]}>Add Markdown</Text>
        </Pressable>
      </Animated.View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  backdropLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  backdropOrb: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 999,
  },
  backdropOrbLeft: {
    top: -56,
    left: -72,
  },
  backdropOrbRight: {
    top: 148,
    right: -88,
  },
  backdropPanel: {
    position: 'absolute',
    top: 248,
    left: spacing.lg,
    right: spacing.lg,
    bottom: 92,
    borderRadius: 36,
  },
  contentContainer: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: 120,
  },
  headerWrap: {
    gap: spacing.lg,
    paddingBottom: spacing.lg,
  },
  heroCard: {
    borderRadius: 32,
    borderWidth: 1,
    padding: spacing.lg,
    gap: spacing.md,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 1,
    shadowRadius: 28,
    elevation: 5,
  },
  heroAccent: {
    width: 72,
    height: 6,
    borderRadius: 999,
  },
  eyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
    letterSpacing: 1.5,
  },
  title: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 36,
    lineHeight: 42,
    maxWidth: 320,
  },
  subtitle: {
    fontFamily: fontFamilies.ui,
    fontSize: 15,
    lineHeight: 24,
    maxWidth: 360,
  },
  heroActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  primaryAction: {
    minHeight: 52,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  primaryActionLabel: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 15,
  },
  secondaryAction: {
    minHeight: 52,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
  },
  secondaryActionLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  metricRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  metricCard: {
    flex: 1,
    minHeight: 84,
    borderRadius: 22,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    justifyContent: 'center',
    gap: spacing.xs,
  },
  metricValue: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 26,
  },
  metricLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    letterSpacing: 0.4,
  },
  controlDeck: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.lg,
    gap: spacing.md,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  controlHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  controlHeaderCopy: {
    flex: 1,
  },
  controlTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 20,
  },
  controlCaption: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
    lineHeight: 22,
    marginTop: spacing.xs,
  },
  controlBadge: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    marginTop: 4,
  },
  themeRow: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  themeChip: {
    minHeight: 44,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  themeChipLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 13,
    textTransform: 'capitalize',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: spacing.xs,
    borderRadius: 999,
    borderWidth: 1,
    padding: 4,
  },
  segment: {
    flex: 1,
    minHeight: 46,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  segmentLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  continueSection: {
    gap: spacing.sm,
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  sectionLabel: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 22,
  },
  sectionMeta: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
  },
  continueRow: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  continueCard: {
    width: 230,
    minHeight: 190,
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.md,
    gap: spacing.sm,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  continueTopBar: {
    width: 64,
    height: 6,
    borderRadius: 999,
  },
  continueTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 20,
    lineHeight: 24,
  },
  continueSnippet: {
    fontFamily: fontFamilies.reading,
    fontSize: 16,
    lineHeight: 25,
    flex: 1,
  },
  continueFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  continueMeta: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
  },
  errorText: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  loadingText: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  tileWrap: {
    marginBottom: spacing.md,
  },
  gridWrap: {
    flex: 1,
  },
  listWrap: {
    width: '100%',
  },
  leftTile: {
    paddingRight: 6,
  },
  rightTile: {
    paddingLeft: 6,
  },
  emptyState: {
    borderRadius: 32,
    borderWidth: 1,
    padding: spacing.xl,
    gap: spacing.md,
    marginTop: spacing.xl,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 1,
    shadowRadius: 28,
    elevation: 5,
  },
  emptyEyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  emptyTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 30,
    lineHeight: 34,
  },
  emptyBody: {
    fontFamily: fontFamilies.ui,
    fontSize: 15,
    lineHeight: 24,
    maxWidth: 340,
  },
  importButton: {
    minHeight: 54,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    alignSelf: 'flex-start',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 5,
  },
  importButtonLabel: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 15,
    color: '#FFFFFF',
  },
  fabWrap: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.xl,
  },
  fab: {
    minWidth: 164,
    minHeight: 58,
    borderRadius: 29,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 6,
  },
  fabLabel: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 15,
  },
});
