// Generated by GitHub Copilot
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Dimensions,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  interpolate,
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
  withTiming,
} from 'react-native-reanimated';

import { MarkdownContent } from '../components/MarkdownContent';
import { useAppContext } from '../state/AppContext';
import { useThemeController } from '../theme/ThemeProvider';
import { fontFamilies, spacing } from '../theme/tokens';
import { RootStackParamList } from '../types';
import { shareDocumentAsHtml, shareDocumentAsPdf } from '../utils/export';

type ReaderScreenProps = NativeStackScreenProps<RootStackParamList, 'Reader'>;

const { height: screenHeight, width: screenWidth } = Dimensions.get('window');

// Keep these in sync with the clamp in AppContext.setFontScale.
const MIN_FONT_SCALE = 0.8;
const MAX_FONT_SCALE = 2.5;

/** Render the immersive document reader with hidden chrome, gestures, and progress tracking. */
export function ReaderScreen({ navigation, route }: ReaderScreenProps) {
  const { documents, setFontScale, setLastOpenedDocumentId, settings, updateProgress } = useAppContext();
  const { tokens } = useThemeController();
  const scrollViewRef = useRef<ScrollView>(null);
  const progressTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [uiVisible, setUiVisible] = useState(true);
  const [hasRestoredPosition, setHasRestoredPosition] = useState(false);
  const translateY = useSharedValue(0);
  const chromeVisibility = useSharedValue(1);
  // Tracks live scroll position on the UI thread so the close gesture can tell
  // whether we are at the very top of the document.
  const scrollOffset = useSharedValue(0);
  const nativeGesture = useMemo(() => Gesture.Native(), []);

  const document = useMemo(
    () => documents.find((item) => item.id === route.params.documentId),
    [documents, route.params.documentId]
  );

  // Live font scale for pinch-to-zoom; renderScale drives layout, the shared
  // value mirrors it for the gesture worklet, and changes persist on release.
  const [renderScale, setRenderScale] = useState(settings.fontScale);
  const liveScale = useSharedValue(settings.fontScale);
  const pinchStartScale = useSharedValue(settings.fontScale);

  // Reading progress (0-1) for the top progress bar, seeded from saved progress.
  const readProgress = useSharedValue(document?.progress ?? 0);

  useEffect(() => {
    // Keep the live scale in sync when settings change (A-/A+ buttons, load).
    liveScale.value = settings.fontScale;
    setRenderScale(settings.fontScale);
  }, [settings.fontScale, liveScale]);

  useEffect(() => {
    void setLastOpenedDocumentId(route.params.documentId);
  }, [route.params.documentId, setLastOpenedDocumentId]);

  useEffect(() => {
    chromeVisibility.value = withTiming(uiVisible ? 1 : 0, { duration: 180 });
  }, [chromeVisibility, uiVisible]);

  useEffect(() => {
    return () => {
      if (progressTimeoutRef.current) {
        clearTimeout(progressTimeoutRef.current);
      }
    };
  }, []);

  /** Toggle chrome only for center taps so scrolling near the edges stays uninterrupted. */
  function handleTap(x: number, y: number) {
    const withinHorizontalSafeZone = x > screenWidth / 3 && x < (screenWidth / 3) * 2;
    const withinVerticalSafeZone = y > screenHeight * 0.2 && y < screenHeight * 0.85;

    if (withinHorizontalSafeZone && withinVerticalSafeZone) {
      setUiVisible((currentVisibility) => !currentVisibility);
    }
  }

  /** Persist reader position with a small delay to avoid excess writes during scrolling. */
  function queueProgressSave(progress: number, offset: number) {
    if (progressTimeoutRef.current) {
      clearTimeout(progressTimeoutRef.current);
    }

    progressTimeoutRef.current = setTimeout(() => {
      void updateProgress(route.params.documentId, progress, offset);
    }, 250);
  }

  /** Open the platform share sheet for HTML or PDF export. */
  function openExportSheet() {
    if (!document) {
      return;
    }

    Alert.alert('Export document', 'Choose a format to share.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Share HTML',
        onPress: () => {
          void shareDocumentAsHtml(document, tokens);
        },
      },
      {
        text: 'Share PDF',
        onPress: () => {
          void shareDocumentAsPdf(document, tokens);
        },
      },
    ]);
  }

  const closeReader = () => navigation.goBack();

  const closeGesture = Gesture.Pan()
    .activeOffsetY([18, 9999])
    // Run alongside the ScrollView so normal scrolling is never blocked.
    .simultaneousWithExternalGesture(nativeGesture)
    .onUpdate((event) => {
      // Only drag the reader away when the content is already at the top and the
      // user is pulling downward; otherwise let the ScrollView own the gesture.
      if (scrollOffset.value <= 0 && event.translationY > 0) {
        translateY.value = event.translationY;
      }
    })
    .onEnd((event) => {
      const shouldDismiss =
        translateY.value > 0 && (event.translationY > 140 || event.velocityY > 950);

      if (shouldDismiss) {
        translateY.value = withTiming(screenHeight, { duration: 180 }, (finished) => {
          if (finished) {
            runOnJS(closeReader)();
          }
        });
      } else {
        translateY.value = withSpring(0, { damping: 18, stiffness: 220 });
      }
    });

  const tapGesture = Gesture.Tap().onEnd((event) => {
    runOnJS(handleTap)(event.x, event.y);
  });

  /** Reflect the live pinch scale into React state so the markdown re-flows. */
  const applyRenderScale = (next: number) => setRenderScale(next);

  /** Persist the final pinch scale once the gesture ends. */
  const commitScale = (next: number) => {
    void setFontScale(next);
  };

  const pinchGesture = Gesture.Pinch()
    .simultaneousWithExternalGesture(nativeGesture)
    .onStart(() => {
      pinchStartScale.value = liveScale.value;
    })
    .onUpdate((event) => {
      let next = pinchStartScale.value * event.scale;
      next = Math.min(Math.max(next, MIN_FONT_SCALE), MAX_FONT_SCALE);
      // Quantize to 0.05 steps so we re-render the document at most a few times.
      next = Math.round(next * 20) / 20;

      if (next !== liveScale.value) {
        liveScale.value = next;
        runOnJS(applyRenderScale)(next);
      }
    })
    .onEnd(() => {
      runOnJS(commitScale)(liveScale.value);
    });

  const gesture = Gesture.Simultaneous(closeGesture, tapGesture, pinchGesture);

  const readerAnimatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: translateY.value }],
    borderRadius: interpolate(translateY.value, [0, 160], [0, 28]),
  }));

  const chromeAnimatedStyle = useAnimatedStyle(() => ({
    opacity: chromeVisibility.value,
    transform: [{ translateY: interpolate(chromeVisibility.value, [0, 1], [-14, 0]) }],
  }));

  const progressFillStyle = useAnimatedStyle(() => ({
    width: `${Math.min(Math.max(readProgress.value, 0), 1) * 100}%`,
  }));

  if (!document) {
    return (
      <SafeAreaView style={[styles.safeArea, { backgroundColor: tokens.background, justifyContent: 'center', alignItems: 'center' }]}>
        <Text style={[styles.missingText, { color: tokens.textSecondary }]}>This document is no longer available.</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: tokens.background }]}>
      <GestureDetector gesture={gesture}>
        <Animated.View style={[styles.readerShell, { backgroundColor: tokens.background }, readerAnimatedStyle]}>
          <View style={[styles.progressTrack, { backgroundColor: tokens.progressTrack }]} pointerEvents="none">
            <Animated.View style={[styles.progressFill, { backgroundColor: tokens.accent }, progressFillStyle]} />
          </View>

          <Animated.View style={[styles.topChrome, chromeAnimatedStyle]}>
            <View style={[styles.topChromeInner, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
              <Pressable onPress={() => navigation.goBack()} style={[styles.chromeButton, { backgroundColor: tokens.surfaceMuted }]}>
                <Text style={[styles.chromeButtonLabel, { color: tokens.textPrimary }]}>Close</Text>
              </Pressable>
              <View style={styles.chromeTitleWrap}>
                <Text style={[styles.chromeEyebrow, { color: tokens.secondary }]}>IMMERSIVE READER</Text>
                <Text numberOfLines={1} style={[styles.chromeTitle, { color: tokens.textPrimary }]}>
                  {document.title}
                </Text>
                <Text style={[styles.chromeMeta, { color: tokens.textMuted }]}>{Math.round(document.progress * 100)}% complete</Text>
              </View>
              <Pressable onPress={() => navigation.navigate('Editor', { documentId: document.id })} style={[styles.chromeButton, { backgroundColor: tokens.surfaceMuted }]}>
                <Text style={[styles.chromeButtonLabel, { color: tokens.textPrimary }]}>Edit</Text>
              </Pressable>
            </View>
          </Animated.View>

          <GestureDetector gesture={nativeGesture}>
          <ScrollView
            ref={scrollViewRef}
            contentContainerStyle={styles.readerContent}
            onContentSizeChange={() => {
              if (!hasRestoredPosition && document.lastReadOffset > 0) {
                scrollViewRef.current?.scrollTo({ y: document.lastReadOffset, animated: false });
                setHasRestoredPosition(true);
              }
            }}
            onScroll={({ nativeEvent }) => {
              scrollOffset.value = nativeEvent.contentOffset.y;
              const totalScrollableHeight = Math.max(nativeEvent.contentSize.height - nativeEvent.layoutMeasurement.height, 1);
              const nextProgress = nativeEvent.contentOffset.y / totalScrollableHeight;
              readProgress.value = Math.min(Math.max(nextProgress, 0), 1);
              queueProgressSave(nextProgress, nativeEvent.contentOffset.y);
            }}
            scrollEventThrottle={16}
            showsVerticalScrollIndicator={true}
          >
            <View style={[styles.readerIntroCard, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
              <View style={[styles.readerIntroBar, { backgroundColor: tokens.secondary }]} />
              <Text style={[styles.readerHeading, { color: tokens.textPrimary }]}>{document.title}</Text>
              <Text style={[styles.readerDeck, { color: tokens.textSecondary }]}>Tap the center to hide chrome. Swipe down to dismiss. Type size and export controls stay close to the thumb zone.</Text>
              <View style={styles.readerMetaRow}>
                <View style={[styles.readerMetaChip, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.readerMetaChipLabel, { color: tokens.textPrimary }]}>{Math.max(1, Math.round(document.wordCount / 220))} min read</Text>
                </View>
                <View style={[styles.readerMetaChip, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.readerMetaChipLabel, { color: tokens.textPrimary }]}>{document.wordCount} words</Text>
                </View>
              </View>
            </View>
            <MarkdownContent content={document.content} fontScale={renderScale} tokens={tokens} />
          </ScrollView>
          </GestureDetector>

          <Animated.View style={[styles.bottomChrome, chromeAnimatedStyle, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
            <Pressable
              onPress={() => void setFontScale(renderScale - 0.1)}
              style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}
            >
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>A-</Text>
            </Pressable>
            <View style={styles.zoomLabelWrap}>
              <Text style={[styles.zoomLabel, { color: tokens.textPrimary }]}>{Math.round(renderScale * 100)}%</Text>
              <Text style={[styles.zoomHint, { color: tokens.textMuted }]}>pinch to zoom</Text>
            </View>
            <Pressable
              onPress={() => void setFontScale(renderScale + 0.1)}
              style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}
            >
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>A+</Text>
            </Pressable>
            <Pressable onPress={openExportSheet} style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}>
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>Share</Text>
            </Pressable>
          </Animated.View>
        </Animated.View>
      </GestureDetector>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  readerShell: {
    flex: 1,
  },
  progressTrack: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    zIndex: 3,
  },
  progressFill: {
    height: '100%',
  },
  topChrome: {
    position: 'absolute',
    top: spacing.lg,
    left: spacing.md,
    right: spacing.md,
    zIndex: 2,
  },
  topChromeInner: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  chromeButton: {
    minHeight: 44,
    minWidth: 72,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
  },
  chromeButtonLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  chromeTitleWrap: {
    flex: 1,
    alignItems: 'center',
    gap: spacing.xs,
  },
  chromeEyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 10,
    letterSpacing: 1.2,
  },
  chromeTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 16,
  },
  chromeMeta: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
  },
  readerContent: {
    paddingTop: 112,
    paddingHorizontal: spacing.lg,
    paddingBottom: 120,
    alignSelf: 'center',
    width: '100%',
    maxWidth: 760,
  },
  readerIntroCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  readerIntroBar: {
    width: 72,
    height: 5,
    borderRadius: 999,
    marginBottom: spacing.sm,
  },
  readerHeading: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 28,
    marginBottom: spacing.xs,
  },
  readerDeck: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: spacing.md,
  },
  readerMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  readerMetaChip: {
    borderRadius: 999,
    minHeight: 34,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  readerMetaChipLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    lineHeight: 16,
  },
  bottomChrome: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.lg,
    minHeight: 76,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: spacing.sm,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  bottomButton: {
    minHeight: 48,
    minWidth: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: spacing.md,
  },
  bottomButtonLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  zoomLabelWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
  },
  zoomLabel: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 15,
  },
  zoomHint: {
    fontFamily: fontFamilies.ui,
    fontSize: 10,
    marginTop: 2,
  },
  missingText: {
    fontFamily: fontFamilies.ui,
    fontSize: 15,
  },
});