// Generated by GitHub Copilot
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Alert,
  Dimensions,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, {
  interpolate,
  runOnJS,
  useAnimatedStyle,
  useSharedValue,
  withSpring,
  withTiming,
} from 'react-native-reanimated';

import { MarkdownContent } from '../components/MarkdownContent';
import { useAppContext } from '../state/AppContext';
import { useThemeController } from '../theme/ThemeProvider';
import { fontFamilies, spacing } from '../theme/tokens';
import { RootStackParamList } from '../types';
import { shareDocumentAsHtml, shareDocumentAsPdf } from '../utils/export';

type ReaderScreenProps = NativeStackScreenProps<RootStackParamList, 'Reader'>;

const { height: screenHeight, width: screenWidth } = Dimensions.get('window');

/** Render the immersive document reader with hidden chrome, gestures, and progress tracking. */
export function ReaderScreen({ navigation, route }: ReaderScreenProps) {
  const { documents, setFontScale, setLastOpenedDocumentId, settings, updateProgress } = useAppContext();
  const { tokens } = useThemeController();
  const scrollViewRef = useRef<ScrollView>(null);
  const progressTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [uiVisible, setUiVisible] = useState(true);
  const [hasRestoredPosition, setHasRestoredPosition] = useState(false);
  const translateY = useSharedValue(0);
  const chromeVisibility = useSharedValue(1);

  const document = useMemo(
    () => documents.find((item) => item.id === route.params.documentId),
    [documents, route.params.documentId]
  );

  useEffect(() => {
    void setLastOpenedDocumentId(route.params.documentId);
  }, [route.params.documentId, setLastOpenedDocumentId]);

  useEffect(() => {
    chromeVisibility.value = withTiming(uiVisible ? 1 : 0, { duration: 180 });
  }, [chromeVisibility, uiVisible]);

  useEffect(() => {
    return () => {
      if (progressTimeoutRef.current) {
        clearTimeout(progressTimeoutRef.current);
      }
    };
  }, []);

  /** Toggle chrome only for center taps so scrolling near the edges stays uninterrupted. */
  function handleTap(x: number, y: number) {
    const withinHorizontalSafeZone = x > screenWidth / 3 && x < (screenWidth / 3) * 2;
    const withinVerticalSafeZone = y > screenHeight * 0.2 && y < screenHeight * 0.85;

    if (withinHorizontalSafeZone && withinVerticalSafeZone) {
      setUiVisible((currentVisibility) => !currentVisibility);
    }
  }

  /** Persist reader position with a small delay to avoid excess writes during scrolling. */
  function queueProgressSave(progress: number, offset: number) {
    if (progressTimeoutRef.current) {
      clearTimeout(progressTimeoutRef.current);
    }

    progressTimeoutRef.current = setTimeout(() => {
      void updateProgress(route.params.documentId, progress, offset);
    }, 250);
  }

  /** Open the platform share sheet for HTML or PDF export. */
  function openExportSheet() {
    if (!document) {
      return;
    }

    Alert.alert('Export document', 'Choose a format to share.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Share HTML',
        onPress: () => {
          void shareDocumentAsHtml(document, tokens);
        },
      },
      {
        text: 'Share PDF',
        onPress: () => {
          void shareDocumentAsPdf(document, tokens);
        },
      },
    ]);
  }

  const closeReader = () => navigation.goBack();

  const closeGesture = Gesture.Pan()
    .activeOffsetY([12, 9999])
    .onUpdate((event) => {
      if (event.translationY > 0) {
        translateY.value = event.translationY;
      }
    })
    .onEnd((event) => {
      if (event.translationY > 140 || event.velocityY > 950) {
        translateY.value = withTiming(screenHeight, { duration: 180 }, (finished) => {
          if (finished) {
            runOnJS(closeReader)();
          }
        });
      } else {
        translateY.value = withSpring(0, { damping: 18, stiffness: 220 });
      }
    });

  const tapGesture = Gesture.Tap().onEnd((event) => {
    runOnJS(handleTap)(event.x, event.y);
  });

  const gesture = Gesture.Simultaneous(closeGesture, tapGesture);

  const readerAnimatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: translateY.value }],
    borderRadius: interpolate(translateY.value, [0, 160], [0, 28]),
  }));

  const chromeAnimatedStyle = useAnimatedStyle(() => ({
    opacity: chromeVisibility.value,
    transform: [{ translateY: interpolate(chromeVisibility.value, [0, 1], [-14, 0]) }],
  }));

  if (!document) {
    return (
      <SafeAreaView style={[styles.safeArea, { backgroundColor: tokens.background, justifyContent: 'center', alignItems: 'center' }]}>
        <Text style={[styles.missingText, { color: tokens.textSecondary }]}>This document is no longer available.</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: tokens.background }]}>
      <GestureDetector gesture={gesture}>
        <Animated.View style={[styles.readerShell, { backgroundColor: tokens.background }, readerAnimatedStyle]}>
          <Animated.View style={[styles.topChrome, chromeAnimatedStyle]}>
            <View style={[styles.topChromeInner, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
              <Pressable onPress={() => navigation.goBack()} style={[styles.chromeButton, { backgroundColor: tokens.surfaceMuted }]}>
                <Text style={[styles.chromeButtonLabel, { color: tokens.textPrimary }]}>Close</Text>
              </Pressable>
              <View style={styles.chromeTitleWrap}>
                <Text style={[styles.chromeEyebrow, { color: tokens.secondary }]}>IMMERSIVE READER</Text>
                <Text numberOfLines={1} style={[styles.chromeTitle, { color: tokens.textPrimary }]}>
                  {document.title}
                </Text>
                <Text style={[styles.chromeMeta, { color: tokens.textMuted }]}>{Math.round(document.progress * 100)}% complete</Text>
              </View>
              <Pressable onPress={() => navigation.navigate('Editor', { documentId: document.id })} style={[styles.chromeButton, { backgroundColor: tokens.surfaceMuted }]}>
                <Text style={[styles.chromeButtonLabel, { color: tokens.textPrimary }]}>Edit</Text>
              </Pressable>
            </View>
          </Animated.View>

          <ScrollView
            ref={scrollViewRef}
            contentContainerStyle={styles.readerContent}
            onContentSizeChange={() => {
              if (!hasRestoredPosition && document.lastReadOffset > 0) {
                scrollViewRef.current?.scrollTo({ y: document.lastReadOffset, animated: false });
                setHasRestoredPosition(true);
              }
            }}
            onScroll={({ nativeEvent }) => {
              const totalScrollableHeight = Math.max(nativeEvent.contentSize.height - nativeEvent.layoutMeasurement.height, 1);
              const nextProgress = nativeEvent.contentOffset.y / totalScrollableHeight;
              queueProgressSave(nextProgress, nativeEvent.contentOffset.y);
            }}
            scrollEventThrottle={16}
            showsVerticalScrollIndicator={false}
          >
            <View style={[styles.readerIntroCard, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}>
              <View style={[styles.readerIntroBar, { backgroundColor: tokens.secondary }]} />
              <Text style={[styles.readerHeading, { color: tokens.textPrimary }]}>{document.title}</Text>
              <Text style={[styles.readerDeck, { color: tokens.textSecondary }]}>Tap the center to hide chrome. Swipe down to dismiss. Type size and export controls stay close to the thumb zone.</Text>
              <View style={styles.readerMetaRow}>
                <View style={[styles.readerMetaChip, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.readerMetaChipLabel, { color: tokens.textPrimary }]}>{Math.max(1, Math.round(document.wordCount / 220))} min read</Text>
                </View>
                <View style={[styles.readerMetaChip, { backgroundColor: tokens.surfaceMuted }]}>
                  <Text style={[styles.readerMetaChipLabel, { color: tokens.textPrimary }]}>{document.wordCount} words</Text>
                </View>
              </View>
            </View>
            <MarkdownContent content={document.content} fontScale={settings.fontScale} tokens={tokens} />
          </ScrollView>

          <Animated.View style={[styles.bottomChrome, chromeAnimatedStyle, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}> 
            <Pressable onPress={() => void setFontScale(settings.fontScale - 0.05)} style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}>
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>A-</Text>
            </Pressable>
            <Pressable onPress={() => void setFontScale(settings.fontScale + 0.05)} style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}>
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>A+</Text>
            </Pressable>
            <Pressable onPress={openExportSheet} style={[styles.bottomButton, { backgroundColor: tokens.surfaceMuted }]}>
              <Text style={[styles.bottomButtonLabel, { color: tokens.textPrimary }]}>Share</Text>
            </Pressable>
          </Animated.View>
        </Animated.View>
      </GestureDetector>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  readerShell: {
    flex: 1,
  },
  topChrome: {
    position: 'absolute',
    top: spacing.lg,
    left: spacing.md,
    right: spacing.md,
    zIndex: 2,
  },
  topChromeInner: {
    minHeight: 78,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  chromeButton: {
    minHeight: 44,
    minWidth: 72,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
  },
  chromeButtonLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  chromeTitleWrap: {
    flex: 1,
    alignItems: 'center',
    gap: spacing.xs,
  },
  chromeEyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 10,
    letterSpacing: 1.2,
  },
  chromeTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 16,
  },
  chromeMeta: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
  },
  readerContent: {
    paddingTop: 112,
    paddingHorizontal: spacing.lg,
    paddingBottom: 120,
    alignSelf: 'center',
    width: '100%',
    maxWidth: 760,
  },
  readerIntroCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  readerIntroBar: {
    width: 72,
    height: 5,
    borderRadius: 999,
    marginBottom: spacing.sm,
  },
  readerHeading: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 28,
    marginBottom: spacing.xs,
  },
  readerDeck: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: spacing.md,
  },
  readerMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  readerMetaChip: {
    borderRadius: 999,
    minHeight: 34,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  readerMetaChipLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    lineHeight: 16,
  },
  bottomChrome: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.lg,
    minHeight: 76,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: spacing.sm,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 20,
    elevation: 5,
  },
  bottomButton: {
    minHeight: 48,
    minWidth: 72,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: spacing.md,
  },
  bottomButtonLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
  },
  missingText: {
    fontFamily: fontFamilies.ui,
    fontSize: 15,
  },
});