// Generated by GitHub Copilot
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { HighlightedText } from '../components/HighlightedText';
import { useAppContext } from '../state/AppContext';
import { useThemeController } from '../theme/ThemeProvider';
import { fontFamilies, spacing } from '../theme/tokens';
import { RootStackParamList, SearchResult } from '../types';

type SearchScreenProps = NativeStackScreenProps<RootStackParamList, 'Search'>;

/** Build a compact snippet around the first matching position in markdown content. */
function createSnippet(content: string, query: string) {
  const normalizedContent = content.replace(/\s+/g, ' ').trim();
  const index = normalizedContent.toLowerCase().indexOf(query.toLowerCase());

  if (index < 0) {
    return normalizedContent.slice(0, 140);
  }

  const start = Math.max(index - 42, 0);
  const end = Math.min(index + query.length + 96, normalizedContent.length);
  return normalizedContent.slice(start, end);
}

/** Count the number of case-insensitive matches for a query within a document. */
function countMatches(text: string, query: string) {
  if (!query.trim()) {
    return 0;
  }

  return text.toLowerCase().split(query.toLowerCase()).length - 1;
}

/** Render search across titles and markdown content with recent query shortcuts. */
export function SearchScreen({ navigation }: SearchScreenProps) {
  const { documents, recentSearches, saveRecentSearchTerm } = useAppContext();
  const { tokens } = useThemeController();
  const [query, setQuery] = useState('');

  const results = useMemo<SearchResult[]>(() => {
    const trimmedQuery = query.trim();

    if (!trimmedQuery) {
      return [];
    }

    return documents
      .map((document) => {
        const totalMatches = countMatches(document.title, trimmedQuery) + countMatches(document.content, trimmedQuery);

        if (!totalMatches) {
          return null;
        }

        return {
          id: document.id,
          title: document.title,
          snippet: createSnippet(document.content, trimmedQuery),
          count: totalMatches,
        };
      })
      .filter(Boolean) as SearchResult[];
  }, [documents, query]);

  /** Open the reader from a search result and store the query for quick reuse. */
  function openResult(documentId: string) {
    if (query.trim()) {
      void saveRecentSearchTerm(query);
    }

    navigation.replace('Reader', { documentId });
  }

  return (
    <View style={[styles.container, { backgroundColor: tokens.background }]}> 
      <View style={[styles.headerCard, { backgroundColor: tokens.surface, borderColor: tokens.outline, shadowColor: tokens.shadow }]}> 
        <Text style={[styles.eyebrow, { color: tokens.secondary }]}>SEARCH THE SHELF</Text>
        <Text style={[styles.title, { color: tokens.textPrimary }]}>Find the line you want, not just the file.</Text>
        <Text style={[styles.subtitle, { color: tokens.textSecondary }]}>Search across titles and body content with calmer results and faster visual scanning.</Text>
      </View>

      <TextInput
        autoFocus
        onChangeText={setQuery}
        placeholder="Search titles and content"
        placeholderTextColor={tokens.textMuted}
        style={[styles.searchInput, { backgroundColor: tokens.surface, color: tokens.textPrimary, borderColor: tokens.outline }]}
        value={query}
      />

      {recentSearches.length ? (
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.recentRow}>
          {recentSearches.map((recentSearch) => (
            <Pressable key={recentSearch} onPress={() => setQuery(recentSearch)} style={[styles.recentChip, { backgroundColor: tokens.surface }]}> 
              <Text style={[styles.recentChipLabel, { color: tokens.textPrimary }]}>{recentSearch}</Text>
            </Pressable>
          ))}
        </ScrollView>
      ) : null}

      <Text style={[styles.resultCount, { color: tokens.textSecondary }]}>
        {query.trim() ? `${results.length} result${results.length === 1 ? '' : 's'}` : 'Type to search your local library'}
      </Text>

      <ScrollView contentContainerStyle={styles.resultList}>
        {query.trim() && !results.length ? (
          <View style={[styles.emptyState, { backgroundColor: tokens.surface }]}> 
            <Text style={[styles.emptyTitle, { color: tokens.textPrimary }]}>No matches found</Text>
            <Text style={[styles.emptyBody, { color: tokens.textSecondary }]}>Try a shorter keyword, a heading, or import another markdown file.</Text>
          </View>
        ) : null}

        {results.map((result) => (
          <Pressable key={result.id} onPress={() => openResult(result.id)} style={[styles.resultCard, { backgroundColor: tokens.surface }]}> 
            <Text style={[styles.resultEyebrow, { color: tokens.textMuted }]}>{result.count} signal hits</Text>
            <HighlightedText
              highlightStyle={{ backgroundColor: tokens.secondary, color: tokens.background }}
              query={query}
              style={[styles.resultTitle, { color: tokens.textPrimary }]}
              text={result.title}
            />
            <HighlightedText
              highlightStyle={{ backgroundColor: tokens.surfaceMuted, color: tokens.textPrimary }}
              query={query}
              style={[styles.resultSnippet, { color: tokens.textSecondary }]}
              text={result.snippet}
            />
            <Text style={[styles.matchCount, { color: tokens.textMuted }]}>{result.count} match{result.count === 1 ? '' : 'es'}</Text>
          </Pressable>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.md,
    gap: spacing.md,
  },
  headerCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.lg,
    gap: spacing.sm,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  eyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
    letterSpacing: 1.4,
  },
  title: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 28,
    lineHeight: 32,
  },
  subtitle: {
    fontFamily: fontFamilies.ui,
    fontSize: 14,
    lineHeight: 22,
  },
  searchInput: {
    minHeight: 58,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    fontFamily: fontFamilies.ui,
    fontSize: 16,
  },
  recentRow: {
    gap: spacing.sm,
    paddingRight: spacing.md,
  },
  recentChip: {
    minHeight: 44,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
  },
  recentChipLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 13,
  },
  resultCount: {
    fontFamily: fontFamilies.ui,
    fontSize: 13,
  },
  resultList: {
    gap: spacing.md,
    paddingBottom: spacing.xl,
  },
  resultCard: {
    borderRadius: 24,
    padding: spacing.md,
    gap: spacing.sm,
  },
  resultEyebrow: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
    letterSpacing: 1,
  },
  resultTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 20,
  },
  resultSnippet: {
    fontFamily: fontFamilies.reading,
    fontSize: 17,
    lineHeight: 28,
  },
  matchCount: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
  },
  emptyState: {
    borderRadius: 24,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  emptyTitle: {
    fontFamily: fontFamilies.uiDisplay,
    fontSize: 22,
  },
  emptyBody: {
    fontFamily: fontFamilies.ui,
    fontSize: 15,
    lineHeight: 22,
  },
});