// Generated by GitHub Copilot
import { DarkTheme, DefaultTheme, Theme as NavigationTheme } from '@react-navigation/native';
import * as SystemUI from 'expo-system-ui';
import React, { PropsWithChildren, createContext, useContext, useEffect, useMemo } from 'react';
import { useColorScheme } from 'react-native';

import { ThemePreference } from '../types';
import { ThemeTokens, getThemeTokens, resolveThemeName } from './tokens';

interface ThemeContextValue {
  tokens: ThemeTokens;
  themeName: ReturnType<typeof resolveThemeName>;
  navigationTheme: NavigationTheme;
  isDark: boolean;
}

const ThemeContext = createContext<ThemeContextValue | null>(null);

/** Provide resolved theme tokens and navigation colors for the current app session. */
export function AppThemeProvider({ children, preference }: PropsWithChildren<{ preference: ThemePreference }>) {
  const systemScheme = useColorScheme();
  const themeName = useMemo(() => resolveThemeName(preference, systemScheme), [preference, systemScheme]);
  const tokens = useMemo(() => getThemeTokens(themeName), [themeName]);
  const isDark = themeName === 'dark' || themeName === 'amoled';

  const navigationTheme = useMemo<NavigationTheme>(() => {
    const baseTheme = isDark ? DarkTheme : DefaultTheme;

    return {
      ...baseTheme,
      colors: {
        ...baseTheme.colors,
        primary: tokens.accent,
        background: tokens.background,
        card: tokens.surface,
        text: tokens.textPrimary,
        border: tokens.outline,
        notification: tokens.secondary,
      },
    };
  }, [isDark, tokens]);

  useEffect(() => {
    void SystemUI.setBackgroundColorAsync(tokens.background);
  }, [tokens.background]);

  const value = useMemo(
    () => ({
      tokens,
      themeName,
      navigationTheme,
      isDark,
    }),
    [isDark, navigationTheme, themeName, tokens]
  );

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
}

/** Return the active theme tokens and derived UI colors. */
export function useThemeController() {
  const context = useContext(ThemeContext);

  if (!context) {
    throw new Error('useThemeController must be used within AppThemeProvider.');
  }

  return context;
}