// Generated by GitHub Copilot
import { ResolvedThemeName, ThemePreference } from '../types';

export interface ThemeTokens {
  background: string;
  surface: string;
  surfaceMuted: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accent: string;
  secondary: string;
  outline: string;
  progressTrack: string;
  shadow: string;
}

export const spacing = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 24,
  xl: 32,
};

export const fontFamilies = {
  ui: 'Inter_500Medium',
  uiDisplay: 'SpaceGrotesk_500Medium',
  reading: 'CrimsonPro_400Regular',
  readingBold: 'CrimsonPro_600SemiBold',
  code: 'JetBrainsMono_500Medium',
};

const themes: Record<ResolvedThemeName, ThemeTokens> = {
  light: {
    background: '#F4EFE8',
    surface: '#FFF9F2',
    surfaceMuted: '#E9DDD0',
    textPrimary: '#1B1714',
    textSecondary: '#5B4D43',
    textMuted: '#8C7C70',
    accent: '#0C6B73',
    secondary: '#B87735',
    outline: '#D9C8B8',
    progressTrack: '#E5D7C8',
    shadow: 'rgba(27, 23, 20, 0.12)',
  },
  dark: {
    background: '#161210',
    surface: '#201A17',
    surfaceMuted: '#312822',
    textPrimary: '#F8F1E7',
    textSecondary: '#D1C2B0',
    textMuted: '#9E8D7D',
    accent: '#66C2C5',
    secondary: '#E2A15A',
    outline: '#3A302A',
    progressTrack: '#463A33',
    shadow: 'rgba(0, 0, 0, 0.42)',
  },
  amoled: {
    background: '#050403',
    surface: '#110E0C',
    surfaceMuted: '#1B1612',
    textPrimary: '#F7F0E6',
    textSecondary: '#C8B8A8',
    textMuted: '#8F7E70',
    accent: '#58D0CF',
    secondary: '#F0AA63',
    outline: '#251E19',
    progressTrack: '#2D241E',
    shadow: 'rgba(0, 0, 0, 0.52)',
  },
  sepia: {
    background: '#EFE4D4',
    surface: '#F9F1E4',
    surfaceMuted: '#E4D3BC',
    textPrimary: '#433228',
    textSecondary: '#6D5648',
    textMuted: '#937A69',
    accent: '#156E76',
    secondary: '#B6702F',
    outline: '#D2BEA2',
    progressTrack: '#DDCDB5',
    shadow: 'rgba(67, 50, 40, 0.14)',
  },
};

/** Resolve the effective reader theme from user preference and system theme. */
export function resolveThemeName(
  preference: ThemePreference,
  systemScheme: 'light' | 'dark' | null | undefined
): ResolvedThemeName {
  if (preference === 'system') {
    return systemScheme === 'dark' ? 'dark' : 'light';
  }

  return preference;
}

/** Return the token set for the active reader theme. */
export function getThemeTokens(themeName: ResolvedThemeName): ThemeTokens {
  return themes[themeName];
}