// Generated by GitHub Copilot
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { ThemeTokens, fontFamilies, spacing } from '../theme/tokens';
import { DocumentRecord, ViewMode } from '../types';

/** Render a document tile for either the bookshelf grid or compact list layout. */
export function FileTile({
  document,
  viewMode,
  tokens,
  fontScale,
  onOpen,
  onToggleFavorite,
  onTogglePin,
  onEdit,
  onDelete,
}: {
  document: DocumentRecord;
  viewMode: ViewMode;
  tokens: ThemeTokens;
  fontScale: number;
  onOpen: () => void;
  onToggleFavorite: () => void;
  onTogglePin: () => void;
  onEdit: () => void;
  onDelete: () => void;
}) {
  const isGrid = viewMode === 'grid';
  const readMinutes = Math.max(1, Math.round(document.wordCount / 220));

  return (
    <Pressable
      accessibilityRole="button"
      onPress={onOpen}
      style={[
        styles.card,
        {
          backgroundColor: tokens.surface,
          borderColor: tokens.outline,
          shadowColor: tokens.shadow,
        },
        isGrid ? styles.gridCard : styles.listCard,
      ]}
    >
      <View style={[styles.coverBand, { backgroundColor: document.favorite ? `${tokens.secondary}20` : `${tokens.accent}18` }]}>
        <Text style={[styles.fileName, { color: tokens.textSecondary }]} numberOfLines={1}>
          {document.fileName}
        </Text>
        <Text style={[styles.fileMeta, { color: tokens.textMuted }]}>{readMinutes} min read</Text>
      </View>

      <View style={styles.cardHeader}>
        <View style={styles.cardHeadingWrap}>
          <Text numberOfLines={2} style={[styles.title, { color: tokens.textPrimary, fontSize: 19 * fontScale }]}>
            {document.title}
          </Text>
          <Text style={[styles.meta, { color: tokens.textMuted }]}>{Math.max(document.wordCount, 1)} words</Text>
        </View>
        <View style={styles.badgeRow}>
          {document.pinned ? <Text style={[styles.badge, { color: tokens.secondary }]}>PINNED</Text> : null}
          {document.favorite ? <Text style={[styles.badge, { color: tokens.accent }]}>STARRED</Text> : null}
        </View>
      </View>

      <View style={[styles.previewPanel, { backgroundColor: tokens.surfaceMuted }]}>
        <Text numberOfLines={isGrid ? 5 : 3} style={[styles.preview, { color: tokens.textSecondary, fontSize: 15 * fontScale }]}>
          {document.preview || 'No preview available.'}
        </Text>
      </View>

      <View style={styles.progressSection}>
        <View style={styles.progressHeader}>
          <Text style={[styles.meta, { color: tokens.textMuted }]}>Reading progress</Text>
          <Text style={[styles.meta, { color: tokens.textPrimary }]}>{Math.round(document.progress * 100)}%</Text>
        </View>
        <View style={[styles.progressTrack, { backgroundColor: tokens.progressTrack }]}>
          <View style={[styles.progressFill, { backgroundColor: tokens.accent, width: `${Math.max(6, document.progress * 100)}%` }]} />
        </View>
      </View>

      <View style={styles.actionRow}>
        <Pressable accessibilityRole="button" onPress={onTogglePin} style={[styles.actionButton, { backgroundColor: tokens.surfaceMuted }]}>
          <Text style={[styles.actionLabel, { color: tokens.textSecondary }]}>{document.pinned ? 'Unpin' : 'Pin'}</Text>
        </Pressable>
        <Pressable accessibilityRole="button" onPress={onToggleFavorite} style={[styles.actionButton, { backgroundColor: tokens.surfaceMuted }]}>
          <Text style={[styles.actionLabel, { color: tokens.textSecondary }]}>{document.favorite ? 'Saved' : 'Star'}</Text>
        </Pressable>
        <Pressable accessibilityRole="button" onPress={onEdit} style={[styles.actionButton, { backgroundColor: tokens.surfaceMuted }]}>
          <Text style={[styles.actionLabel, { color: tokens.textSecondary }]}>Edit</Text>
        </Pressable>
        <Pressable accessibilityRole="button" onPress={onDelete} style={[styles.actionButton, { backgroundColor: `${tokens.secondary}14` }]}>
          <Text style={[styles.actionLabel, { color: '#C95D5D' }]}>Delete</Text>
        </Pressable>
      </View>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  card: {
    borderRadius: 28,
    borderWidth: 1,
    padding: spacing.md,
    gap: spacing.sm,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 1,
    shadowRadius: 24,
    elevation: 4,
  },
  gridCard: {
    minHeight: 330,
  },
  listCard: {
    minHeight: 244,
  },
  coverBand: {
    minHeight: 58,
    borderRadius: 18,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    justifyContent: 'space-between',
  },
  fileName: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    letterSpacing: 0.4,
  },
  fileMeta: {
    fontFamily: fontFamilies.ui,
    fontSize: 11,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cardHeadingWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  title: {
    fontFamily: fontFamilies.uiDisplay,
    lineHeight: 24,
  },
  previewPanel: {
    borderRadius: 20,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flex: 1,
  },
  preview: {
    fontFamily: fontFamilies.reading,
    lineHeight: 24,
  },
  meta: {
    fontFamily: fontFamilies.ui,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  badgeRow: {
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  badge: {
    fontFamily: fontFamilies.ui,
    fontSize: 10,
    letterSpacing: 0.9,
  },
  progressSection: {
    gap: spacing.xs,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  actionButton: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
  },
  actionLabel: {
    fontFamily: fontFamilies.ui,
    fontSize: 13,
  },
});
