// Generated by GitHub Copilot
import React from 'react';
import { StyleProp, Text, TextStyle } from 'react-native';

/** Escape regex control characters before building a search expression. */
function escapeRegExp(input: string) {
  return input.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Render text with highlighted segments for inline search result emphasis. */
export function HighlightedText({
  text,
  query,
  style,
  highlightStyle,
}: {
  text: string;
  query: string;
  style?: StyleProp<TextStyle>;
  highlightStyle?: StyleProp<TextStyle>;
}) {
  if (!query.trim()) {
    return <Text style={style}>{text}</Text>;
  }

  const expression = new RegExp(`(${escapeRegExp(query)})`, 'ig');
  const parts = text.split(expression);

  return (
    <Text style={style}>
      {parts.map((part, index) => {
        const isMatch = part.toLowerCase() === query.toLowerCase();

        return (
          <Text key={`${part}-${index}`} style={isMatch ? highlightStyle : undefined}>
            {part}
          </Text>
        );
      })}
    </Text>
  );
}