// Generated by GitHub Copilot
import React, { useMemo } from 'react';
import { Linking, ScrollView, StyleSheet, Text, View } from 'react-native';
import Markdown from 'react-native-markdown-display';

import { ThemeTokens, fontFamilies } from '../theme/tokens';

/** Render markdown using typography tuned for long-form mobile reading. */
export function MarkdownContent({
  content,
  tokens,
  fontScale,
}: {
  content: string;
  tokens: ThemeTokens;
  fontScale: number;
}) {
  const markdownStyles = useMemo(
    () =>
      StyleSheet.create({
        body: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 33 * fontScale,
        },
        heading1: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 32 * fontScale,
          marginTop: 12,
          marginBottom: 16,
        },
        heading2: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 24 * fontScale,
          marginTop: 18,
          marginBottom: 12,
        },
        heading3: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 20 * fontScale,
          marginTop: 16,
          marginBottom: 8,
        },
        paragraph: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 33 * fontScale,
          marginBottom: 16,
        },
        list_item: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 30 * fontScale,
        },
        blockquote: {
          borderLeftColor: tokens.accent,
          backgroundColor: tokens.surfaceMuted,
          borderLeftWidth: 4,
          paddingHorizontal: 16,
          paddingVertical: 12,
          borderRadius: 16,
        },
        code_inline: {
          color: tokens.textPrimary,
          backgroundColor: tokens.surfaceMuted,
          fontFamily: fontFamilies.code,
          borderRadius: 8,
          paddingHorizontal: 8,
          paddingVertical: 4,
        },
        fence: {
          color: tokens.textPrimary,
          backgroundColor: tokens.surfaceMuted,
          fontFamily: fontFamilies.code,
          borderRadius: 18,
          padding: 16,
          marginBottom: 16,
        },
        // Container + text styles used by the custom horizontally-scrolling
        // code block renderer below.
        codeContainer: {
          backgroundColor: tokens.surfaceMuted,
          borderRadius: 18,
          marginBottom: 16,
        },
        codeScroll: {
          padding: 16,
        },
        codeText: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.code,
          fontSize: 15 * fontScale,
          lineHeight: 22 * fontScale,
        },
        tableScroll: {
          marginBottom: 16,
        },
        table: {
          borderWidth: 1,
          borderColor: tokens.outline,
          borderRadius: 12,
          overflow: 'hidden',
        },
        tr: {
          flexDirection: 'row',
        },
        th: {
          minWidth: 132,
          padding: 10,
          borderColor: tokens.outline,
          borderRightWidth: 1,
          borderBottomWidth: 1,
        },
        td: {
          minWidth: 132,
          padding: 10,
          borderColor: tokens.outline,
          borderRightWidth: 1,
          borderBottomWidth: 1,
        },
        image: {
          borderRadius: 20,
          marginVertical: 8,
        },
        link: {
          color: tokens.accent,
        },
      }),
    [fontScale, tokens]
  );

  // Render wide code blocks and tables inside a horizontal ScrollView so long
  // lines and many columns stay readable instead of being cramped or clipped.
  const rules = useMemo(
    () => ({
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      fence: (node: any) => (
        <View key={node.key} style={markdownStyles.codeContainer}>
          <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={markdownStyles.codeScroll}>
            <Text style={markdownStyles.codeText}>{node.content}</Text>
          </ScrollView>
        </View>
      ),
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      code_block: (node: any) => (
        <View key={node.key} style={markdownStyles.codeContainer}>
          <ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={markdownStyles.codeScroll}>
            <Text style={markdownStyles.codeText}>{node.content}</Text>
          </ScrollView>
        </View>
      ),
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      table: (node: any, children: React.ReactNode) => (
        <ScrollView key={node.key} horizontal showsHorizontalScrollIndicator style={markdownStyles.tableScroll}>
          <View style={markdownStyles.table}>{children}</View>
        </ScrollView>
      ),
    }),
    [markdownStyles]
  );

  return (
    <Markdown
      style={markdownStyles}
      rules={rules}
      onLinkPress={(url) => {
        void Linking.openURL(url);
        return false;
      }}
    >
      {content}
    </Markdown>
  );
}