// Generated by GitHub Copilot
import React, { useMemo } from 'react';
import { Linking, StyleSheet } from 'react-native';
import Markdown from 'react-native-markdown-display';

import { ThemeTokens, fontFamilies } from '../theme/tokens';

/** Render markdown using typography tuned for long-form mobile reading. */
export function MarkdownContent({
  content,
  tokens,
  fontScale,
}: {
  content: string;
  tokens: ThemeTokens;
  fontScale: number;
}) {
  const markdownStyles = useMemo(
    () =>
      StyleSheet.create({
        body: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 33 * fontScale,
        },
        heading1: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 32 * fontScale,
          marginTop: 12,
          marginBottom: 16,
        },
        heading2: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 24 * fontScale,
          marginTop: 18,
          marginBottom: 12,
        },
        heading3: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.uiDisplay,
          fontSize: 20 * fontScale,
          marginTop: 16,
          marginBottom: 8,
        },
        paragraph: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 33 * fontScale,
          marginBottom: 16,
        },
        list_item: {
          color: tokens.textPrimary,
          fontFamily: fontFamilies.reading,
          fontSize: 19 * fontScale,
          lineHeight: 30 * fontScale,
        },
        blockquote: {
          borderLeftColor: tokens.accent,
          backgroundColor: tokens.surfaceMuted,
          borderLeftWidth: 4,
          paddingHorizontal: 16,
          paddingVertical: 12,
          borderRadius: 16,
        },
        code_inline: {
          color: tokens.textPrimary,
          backgroundColor: tokens.surfaceMuted,
          fontFamily: fontFamilies.code,
          borderRadius: 8,
          paddingHorizontal: 8,
          paddingVertical: 4,
        },
        fence: {
          color: tokens.textPrimary,
          backgroundColor: tokens.surfaceMuted,
          fontFamily: fontFamilies.code,
          borderRadius: 18,
          padding: 16,
          marginBottom: 16,
        },
        image: {
          borderRadius: 20,
          marginVertical: 8,
        },
        link: {
          color: tokens.accent,
        },
      }),
    [fontScale, tokens]
  );

  return (
    <Markdown
      style={markdownStyles}
      onLinkPress={(url) => {
        void Linking.openURL(url);
        return false;
      }}
    >
      {content}
    </Markdown>
  );
}