// Generated by GitHub Copilot
import { Paths } from 'expo-file-system';
import * as LegacyFileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { marked } from 'marked';

import { ThemeTokens } from '../theme/tokens';
import { DocumentRecord } from '../types';

/** Build an HTML document for export using the active reading theme. */
export function buildHtmlDocument(document: DocumentRecord, tokens: ThemeTokens) {
  const renderedMarkdown = marked.parse(document.content) as string;

  return `<!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>${document.title}</title>
      <style>
        body {
          margin: 0;
          padding: 40px 24px;
          font-family: "Crimson Pro", Georgia, serif;
          background: ${tokens.background};
          color: ${tokens.textPrimary};
          line-height: 1.72;
          max-width: 760px;
        }
        h1, h2, h3, h4, h5, h6 {
          font-family: "Space Grotesk", Arial, sans-serif;
          color: ${tokens.textPrimary};
        }
        code, pre {
          font-family: "JetBrains Mono", monospace;
          background: ${tokens.surfaceMuted};
          border-radius: 12px;
        }
        pre {
          padding: 16px;
          overflow: auto;
        }
        img {
          max-width: 100%;
          border-radius: 16px;
        }
        a {
          color: ${tokens.accent};
        }
      </style>
    </head>
    <body>
      ${renderedMarkdown}
    </body>
  </html>`;
}

/** Share a rendered HTML version of the current markdown document. */
export async function shareDocumentAsHtml(document: DocumentRecord, tokens: ThemeTokens) {
  const html = buildHtmlDocument(document, tokens);

  if (!Paths.cache?.uri) {
    throw new Error('Cache directory is unavailable on this platform.');
  }

  const filePath = `${Paths.cache.uri}${document.id}.html`;
  await LegacyFileSystem.writeAsStringAsync(filePath, html, { encoding: 'utf8' });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(filePath, {
      mimeType: 'text/html',
      dialogTitle: `Share ${document.title}`,
    });
  }
}

/** Render the current markdown document to PDF and share it. */
export async function shareDocumentAsPdf(document: DocumentRecord, tokens: ThemeTokens) {
  const html = buildHtmlDocument(document, tokens);
  const file = await Print.printToFileAsync({ html });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(file.uri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share ${document.title}`,
      UTI: 'com.adobe.pdf',
    });
  }
}