// Generated by GitHub Copilot
import * as DocumentPicker from 'expo-document-picker';
import * as Haptics from 'expo-haptics';
import React, { PropsWithChildren, createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

import { AppSettings, DocumentRecord } from '../types';
import {
  deleteDocument,
  importDocumentFromAsset,
  initializeStorage,
  loadAppSnapshot,
  recordRecentSearch,
  saveDocumentContent,
  saveSettings,
  updateDocumentMetadata,
} from '../storage/library';

interface AppContextValue {
  loading: boolean;
  error: string | null;
  documents: DocumentRecord[];
  settings: AppSettings;
  recentSearches: string[];
  refreshLibrary: () => Promise<void>;
  importDocument: () => Promise<void>;
  toggleFavorite: (documentId: string) => Promise<void>;
  togglePin: (documentId: string) => Promise<void>;
  removeDocument: (documentId: string) => Promise<void>;
  saveDocument: (documentId: string, content: string) => Promise<void>;
  updateProgress: (documentId: string, progress: number, lastReadOffset: number) => Promise<void>;
  setThemePreference: (themePreference: AppSettings['themePreference']) => Promise<void>;
  setViewMode: (viewMode: AppSettings['viewMode']) => Promise<void>;
  setFontScale: (fontScale: number) => Promise<void>;
  setLastOpenedDocumentId: (documentId: string | null) => Promise<void>;
  saveRecentSearchTerm: (term: string) => Promise<void>;
}

const AppContext = createContext<AppContextValue | null>(null);

const defaultSettings: AppSettings = {
  themePreference: 'system',
  viewMode: 'grid',
  fontScale: 1,
  lastOpenedDocumentId: null,
};

/** Provide persisted library state and all document management actions to the app. */
export function AppProvider({ children }: PropsWithChildren) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [documents, setDocuments] = useState<DocumentRecord[]>([]);
  const [settings, setSettingsState] = useState<AppSettings>(defaultSettings);
  const [recentSearches, setRecentSearches] = useState<string[]>([]);

  /** Reload the persisted app state from SQLite after any library mutation. */
  const refreshLibrary = useCallback(async () => {
    const snapshot = await loadAppSnapshot();
    setDocuments(snapshot.documents);
    setSettingsState(snapshot.settings);
    setRecentSearches(snapshot.recentSearches);
  }, []);

  /** Bootstrap the local storage schema and hydrate the app snapshot. */
  const bootstrap = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      await initializeStorage();
      await refreshLibrary();
    } catch (storageError) {
      setError(storageError instanceof Error ? storageError.message : 'Unable to load the library.');
    } finally {
      setLoading(false);
    }
  }, [refreshLibrary]);

  useEffect(() => {
    void bootstrap();
  }, [bootstrap]);

  /** Import a markdown file through the native picker. */
  const importDocument = useCallback(async () => {
    // Many file managers tag .md files as octet-stream or leave them untyped, so
    // accept any file to keep them selectable; non-text content simply fails to read.
    const result = await DocumentPicker.getDocumentAsync({
      type: '*/*',
      copyToCacheDirectory: true,
      multiple: false,
    });

    if (result.canceled || !result.assets?.length) {
      return;
    }

    await importDocumentFromAsset(result.assets[0]);
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    await refreshLibrary();
  }, [refreshLibrary]);

  /** Flip the favorite state for one document. */
  const toggleFavorite = useCallback(
    async (documentId: string) => {
      const currentDocument = documents.find((document) => document.id === documentId);

      if (!currentDocument) {
        return;
      }

      await updateDocumentMetadata(documentId, { favorite: !currentDocument.favorite });
      await Haptics.selectionAsync();
      await refreshLibrary();
    },
    [documents, refreshLibrary]
  );

  /** Flip the pin state for one document. */
  const togglePin = useCallback(
    async (documentId: string) => {
      const currentDocument = documents.find((document) => document.id === documentId);

      if (!currentDocument) {
        return;
      }

      await updateDocumentMetadata(documentId, { pinned: !currentDocument.pinned });
      await Haptics.selectionAsync();
      await refreshLibrary();
    },
    [documents, refreshLibrary]
  );

  /** Remove a markdown file from the local library and storage sandbox. */
  const removeDocument = useCallback(
    async (documentId: string) => {
      await deleteDocument(documentId);
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      await refreshLibrary();
    },
    [refreshLibrary]
  );

  /** Persist editor changes to SQLite and the on-disk markdown copy. */
  const saveDocument = useCallback(
    async (documentId: string, content: string) => {
      await saveDocumentContent(documentId, content);
      await refreshLibrary();
    },
    [refreshLibrary]
  );

  /** Persist the current reader progress and last known scroll position. */
  const updateProgress = useCallback(async (documentId: string, progress: number, lastReadOffset: number) => {
    await updateDocumentMetadata(documentId, {
      progress: Number.isFinite(progress) ? Math.min(Math.max(progress, 0), 1) : 0,
      lastReadOffset: Number.isFinite(lastReadOffset) ? Math.max(lastReadOffset, 0) : 0,
    });
  }, []);

  /** Save the theme preference and immediately reflect it in the UI. */
  const setThemePreference = useCallback(async (themePreference: AppSettings['themePreference']) => {
    setSettingsState((currentSettings) => ({ ...currentSettings, themePreference }));
    await saveSettings({ themePreference });
  }, []);

  /** Save the active library layout mode. */
  const setViewMode = useCallback(async (viewMode: AppSettings['viewMode']) => {
    setSettingsState((currentSettings) => ({ ...currentSettings, viewMode }));
    await saveSettings({ viewMode });
  }, []);

  /** Save the reader font scale with a comfort-first clamp. */
  const setFontScale = useCallback(async (fontScale: number) => {
    const nextScale = Math.min(Math.max(Number(fontScale.toFixed(2)), 0.8), 2.5);
    setSettingsState((currentSettings) => ({ ...currentSettings, fontScale: nextScale }));
    await saveSettings({ fontScale: nextScale });
  }, []);

  /** Track the last opened document for quick continuation. */
  const setLastOpenedDocumentId = useCallback(async (documentId: string | null) => {
    setSettingsState((currentSettings) => ({ ...currentSettings, lastOpenedDocumentId: documentId }));
    await saveSettings({ lastOpenedDocumentId: documentId });
  }, []);

  /** Save a recent query for faster follow-up search. */
  const saveRecentSearchTerm = useCallback(async (term: string) => {
    await recordRecentSearch(term);
    const snapshot = await loadAppSnapshot();
    setRecentSearches(snapshot.recentSearches);
  }, []);

  const value = useMemo<AppContextValue>(
    () => ({
      loading,
      error,
      documents,
      settings,
      recentSearches,
      refreshLibrary,
      importDocument,
      toggleFavorite,
      togglePin,
      removeDocument,
      saveDocument,
      updateProgress,
      setThemePreference,
      setViewMode,
      setFontScale,
      setLastOpenedDocumentId,
      saveRecentSearchTerm,
    }),
    [
      documents,
      error,
      importDocument,
      loading,
      recentSearches,
      refreshLibrary,
      removeDocument,
      saveDocument,
      saveRecentSearchTerm,
      setFontScale,
      setLastOpenedDocumentId,
      setThemePreference,
      setViewMode,
      settings,
      toggleFavorite,
      togglePin,
      updateProgress,
    ]
  );

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

/** Access the app library state and actions from within the provider tree. */
export function useAppContext() {
  const context = useContext(AppContext);

  if (!context) {
    throw new Error('useAppContext must be used within AppProvider.');
  }

  return context;
}