// Generated by GitHub Copilot
import * as DocumentPicker from 'expo-document-picker';
import { Paths } from 'expo-file-system';
import * as LegacyFileSystem from 'expo-file-system/legacy';
import * as SQLite from 'expo-sqlite';

import { AppSettings, DocumentRecord, ThemePreference, ViewMode } from '../types';

const DATABASE_NAME = 'md-reader.db';
const LIBRARY_DIRECTORY_NAME = 'md-reader-library';

const defaultSettings: AppSettings = {
  themePreference: 'system',
  viewMode: 'grid',
  fontScale: 1,
  lastOpenedDocumentId: null,
};

const sampleDocuments = [
  {
    fileName: 'welcome.md',
    content: `# Welcome to MD Reader

MD Reader is built for long sessions, not quick taps. Typography stays calm, controls stay nearby, and every file lives offline once it reaches the shelf.

## Try this first

- Open the library and switch between Gallery and Editorial layouts.
- Tap into the reader and hide the chrome with a center tap.
- Adjust the type scale from the reader footer.
- Open the editor and test live preview with markdown shortcuts.

> The best reading apps disappear just enough to let the text take over.

## Why this starter exists

This project bundles local file import, persistent progress, search, sharing, and a premium reading surface so you can start from a polished base instead of a blank shell.
`,
  },
  {
    fileName: 'deep-reading.md',
    content: `# Deep Reading Notes

Long-form reading works best when motion is soft, line lengths are moderate, and the interface does not compete with the document.

## Comfort first

Generous line height, stable spacing, and predictable controls reduce fatigue.

## Build a working set

- Pin documents you return to every day.
- Favorite the writing that deserves a second pass.
- Use Continue Reading as a lightweight queue.

## Small rituals matter

Search for a phrase. Reopen where you left off. Export a clean PDF. The details are what make a reader feel expensive.
`,
  },
  {
    fileName: 'field-notes.md',
    content: `# Field Notes for a Premium App

## Sensory checklist

- Strong first screen
- Clear hierarchy
- Quiet but not bland color
- Fast transitions
- Export and edit within reach

## Microcopy

Short labels do more work than clever labels.

## Sample code block

\`\`\`ts
const ritual = {
  open: 'library',
  focus: 'reader',
  finish: 'share',
};
\`\`\`

## Closing note

Luxury in software is often restraint plus consistency.
`,
  },
  {
    fileName: 'weekend-essay.md',
    content: `# Weekend Essay

The room was quiet enough to hear page turns in the next apartment. Morning light hit the desk in a thin gold band, and the whole point of the app became obvious: remove every excuse to stop reading.

## What makes a reader feel good

1. The first screen should feel deliberate.
2. The typography should look chosen.
3. The controls should stay out of the way until they are needed.

## A line worth keeping

> Interfaces feel premium when they spend their energy on pacing, not decoration.
`,
  },
  {
    fileName: 'launch-checklist.md',
    content: `# Launch Checklist

## Before shipping

- Review empty states
- Test import on a real device
- Verify search snippets
- Export one file as HTML
- Export one file as PDF

## Sample link

[Read the Expo docs](https://docs.expo.dev)

## Final thought

The seeded library should teach the app in under two minutes.
`,
  },
];

interface DbDocumentRow {
  id: string;
  title: string;
  file_name: string;
  local_uri: string;
  content: string;
  preview: string;
  word_count: number;
  created_at: number;
  updated_at: number;
  progress: number;
  last_read_offset: number;
  favorite: number;
  pinned: number;
}

let databasePromise: Promise<SQLite.SQLiteDatabase> | null = null;

/** Return the singleton SQLite connection used by the app. */
async function getDatabase() {
  if (!databasePromise) {
    databasePromise = SQLite.openDatabaseAsync(DATABASE_NAME);
  }

  return databasePromise;
}

/** Return the sandbox directory where imported markdown files are stored. */
function getLibraryDirectory() {
    if (!Paths.document?.uri) {
    throw new Error('Document directory is unavailable on this platform.');
  }

    return `${Paths.document.uri}${LIBRARY_DIRECTORY_NAME}`;
}

/** Create a filesystem-safe slug from the original file name or document title. */
function slugify(input: string) {
  return input
    .toLowerCase()
    .replace(/\.md$/i, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

/** Derive a reader-friendly document title from markdown content. */
function deriveTitle(content: string, fallbackFileName: string) {
  const firstHeading = content
    .split(/\r?\n/)
    .find((line) => line.trim().startsWith('#'))
    ?.replace(/^#+\s*/, '')
    .trim();

  return firstHeading || fallbackFileName.replace(/\.md$/i, '') || 'Untitled Document';
}

/** Build a compact preview snippet for library cards and search results. */
function createPreview(content: string) {
  return content
    .replace(/[`*_>#\-\[\]!]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 180);
}

/** Count words for quick document metadata and reading stats. */
function countWords(content: string) {
  return content.trim().split(/\s+/).filter(Boolean).length;
}

/** Ensure the sandbox folder for imported markdown exists before file operations. */
async function ensureLibraryDirectory() {
  const libraryDirectory = getLibraryDirectory();
  const directoryInfo = await LegacyFileSystem.getInfoAsync(libraryDirectory);

  if (!directoryInfo.exists) {
    await LegacyFileSystem.makeDirectoryAsync(libraryDirectory, { intermediates: true });
  }

  return libraryDirectory;
}

/** Map a SQLite row into the in-memory document model used by the UI. */
function mapDocumentRow(row: DbDocumentRow): DocumentRecord {
  return {
    id: row.id,
    title: row.title,
    fileName: row.file_name,
    localUri: row.local_uri,
    content: row.content,
    preview: row.preview,
    wordCount: row.word_count,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    progress: row.progress,
    lastReadOffset: row.last_read_offset,
    favorite: Boolean(row.favorite),
    pinned: Boolean(row.pinned),
  };
}

/** Sort documents with pins first, then favorites, then recent activity. */
function sortDocuments(documents: DocumentRecord[]) {
  return [...documents].sort((left, right) => {
    if (left.pinned !== right.pinned) {
      return Number(right.pinned) - Number(left.pinned);
    }

    if (left.favorite !== right.favorite) {
      return Number(right.favorite) - Number(left.favorite);
    }

    return right.updatedAt - left.updatedAt;
  });
}

/** Persist a document row to SQLite and keep the markdown file in sync on disk. */
async function upsertDocument(document: DocumentRecord) {
  const database = await getDatabase();

  await database.runAsync(
    `INSERT INTO documents (
      id,
      title,
      file_name,
      local_uri,
      content,
      preview,
      word_count,
      created_at,
      updated_at,
      progress,
      last_read_offset,
      favorite,
      pinned
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      title = excluded.title,
      file_name = excluded.file_name,
      local_uri = excluded.local_uri,
      content = excluded.content,
      preview = excluded.preview,
      word_count = excluded.word_count,
      updated_at = excluded.updated_at,
      progress = excluded.progress,
      last_read_offset = excluded.last_read_offset,
      favorite = excluded.favorite,
      pinned = excluded.pinned`,
    [
      document.id,
      document.title,
      document.fileName,
      document.localUri,
      document.content,
      document.preview,
      document.wordCount,
      document.createdAt,
      document.updatedAt,
      document.progress,
      document.lastReadOffset,
      Number(document.favorite),
      Number(document.pinned),
    ]
  );

    await LegacyFileSystem.writeAsStringAsync(document.localUri, document.content, {
      encoding: 'utf8',
  });
}

/** Create a stored document model from raw markdown text. */
async function createStoredDocument(fileName: string, content: string) {
  const libraryDirectory = await ensureLibraryDirectory();
  const now = Date.now();
  const safeName = `${slugify(fileName || 'document') || 'document'}-${now}.md`;
  const localUri = `${libraryDirectory}/${safeName}`;
  const title = deriveTitle(content, fileName || safeName);

  const document: DocumentRecord = {
    id: `${slugify(title) || 'doc'}-${now}`,
    title,
    fileName: safeName,
    localUri,
    content,
    preview: createPreview(content),
    wordCount: countWords(content),
    createdAt: now,
    updatedAt: now,
    progress: 0,
    lastReadOffset: 0,
    favorite: false,
    pinned: false,
  };

  await upsertDocument(document);
  return document;
}

/** Seed the library with sample markdown if the user has not imported anything yet. */
async function seedInitialDocuments() {
  for (const sampleDocument of sampleDocuments) {
    await createStoredDocument(sampleDocument.fileName, sampleDocument.content);
  }
}

/** Add any starter markdown documents that are not already present in the library. */
async function seedMissingSampleDocuments() {
  const database = await getDatabase();
  const existingRows = await database.getAllAsync<{ title: string }>('SELECT title FROM documents');
  const existingTitles = new Set(existingRows.map((row) => row.title));

  for (const sampleDocument of sampleDocuments) {
    const sampleTitle = deriveTitle(sampleDocument.content, sampleDocument.fileName);

    if (!existingTitles.has(sampleTitle)) {
      await createStoredDocument(sampleDocument.fileName, sampleDocument.content);
      existingTitles.add(sampleTitle);
    }
  }
}

/** Initialize the database schema and seed starter content for an empty library. */
export async function initializeStorage() {
  const database = await getDatabase();

  await database.execAsync(`
    CREATE TABLE IF NOT EXISTS documents (
      id TEXT PRIMARY KEY NOT NULL,
      title TEXT NOT NULL,
      file_name TEXT NOT NULL,
      local_uri TEXT NOT NULL,
      content TEXT NOT NULL,
      preview TEXT NOT NULL,
      word_count INTEGER NOT NULL,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      progress REAL NOT NULL DEFAULT 0,
      last_read_offset REAL NOT NULL DEFAULT 0,
      favorite INTEGER NOT NULL DEFAULT 0,
      pinned INTEGER NOT NULL DEFAULT 0
    );
    CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY NOT NULL,
      value TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS recent_searches (
      term TEXT PRIMARY KEY NOT NULL,
      used_at INTEGER NOT NULL
    );
  `);

  await ensureLibraryDirectory();

  const existingDocuments = await database.getFirstAsync<{ count: number }>('SELECT COUNT(*) as count FROM documents');

  if (!existingDocuments?.count) {
    await seedInitialDocuments();
    return;
  }

  await seedMissingSampleDocuments();
}

/** Load the full persisted app snapshot for library, settings, and recent searches. */
export async function loadAppSnapshot() {
  const database = await getDatabase();
  const documentRows = await database.getAllAsync<DbDocumentRow>('SELECT * FROM documents');
  const settingsRows = await database.getAllAsync<{ key: string; value: string }>('SELECT key, value FROM settings');
  const recentRows = await database.getAllAsync<{ term: string }>('SELECT term FROM recent_searches ORDER BY used_at DESC LIMIT 6');

  const settings = settingsRows.reduce<AppSettings>((accumulator, row) => {
    const parsedValue = JSON.parse(row.value);

    if (row.key === 'themePreference') {
      accumulator.themePreference = parsedValue as ThemePreference;
    }

    if (row.key === 'viewMode') {
      accumulator.viewMode = parsedValue as ViewMode;
    }

    if (row.key === 'fontScale') {
      accumulator.fontScale = parsedValue as number;
    }

    if (row.key === 'lastOpenedDocumentId') {
      accumulator.lastOpenedDocumentId = parsedValue as string | null;
    }

    return accumulator;
  }, { ...defaultSettings });

  return {
    documents: sortDocuments(documentRows.map(mapDocumentRow)),
    settings,
    recentSearches: recentRows.map((row) => row.term),
  };
}

/** Import a markdown document selected from the native file picker into app storage. */
export async function importDocumentFromAsset(asset: DocumentPicker.DocumentPickerAsset) {
  const content = await LegacyFileSystem.readAsStringAsync(asset.uri, {
      encoding: 'utf8',
  });

  return createStoredDocument(asset.name || 'imported-document.md', content);
}

/** Import a markdown document directly from a URI (e.g. from an Android Intent). */
export async function importDocumentFromUri(uri: string) {
  const content = await LegacyFileSystem.readAsStringAsync(uri, {
      encoding: 'utf8',
  });

  let fileName = 'shared-document.md';
  const uriParts = uri.split('/');
  const lastPart = uriParts[uriParts.length - 1];
  if (lastPart && lastPart.includes('.')) {
      fileName = decodeURIComponent(lastPart);
  }

  return createStoredDocument(fileName, content);
}

/** Save edited markdown content and refresh its derived metadata. */
export async function saveDocumentContent(documentId: string, content: string) {
  const snapshot = await loadAppSnapshot();
  const existingDocument = snapshot.documents.find((document) => document.id === documentId);

  if (!existingDocument) {
    throw new Error('Document not found.');
  }

  const updatedDocument: DocumentRecord = {
    ...existingDocument,
    title: deriveTitle(content, existingDocument.fileName),
    content,
    preview: createPreview(content),
    wordCount: countWords(content),
    updatedAt: Date.now(),
  };

  await upsertDocument(updatedDocument);
  return updatedDocument;
}

/** Update reader-specific metadata like progress, pinning, and favorites. */
export async function updateDocumentMetadata(
  documentId: string,
  patch: Partial<Pick<DocumentRecord, 'favorite' | 'pinned' | 'progress' | 'lastReadOffset'>>
) {
  const snapshot = await loadAppSnapshot();
  const existingDocument = snapshot.documents.find((document) => document.id === documentId);

  if (!existingDocument) {
    throw new Error('Document not found.');
  }

  const updatedDocument: DocumentRecord = {
    ...existingDocument,
    ...patch,
    updatedAt: patch.progress !== undefined ? existingDocument.updatedAt : Date.now(),
  };

  await upsertDocument(updatedDocument);
  return updatedDocument;
}

/** Delete a document from SQLite and remove the stored markdown file from disk. */
export async function deleteDocument(documentId: string) {
  const snapshot = await loadAppSnapshot();
  const existingDocument = snapshot.documents.find((document) => document.id === documentId);

  if (!existingDocument) {
    return;
  }

  const database = await getDatabase();
  await database.runAsync('DELETE FROM documents WHERE id = ?', [documentId]);

  const fileInfo = await LegacyFileSystem.getInfoAsync(existingDocument.localUri);

  if (fileInfo.exists) {
    await LegacyFileSystem.deleteAsync(existingDocument.localUri, { idempotent: true });
  }
}

/** Persist a partial settings update without disturbing saved preferences. */
export async function saveSettings(settingsPatch: Partial<AppSettings>) {
  const database = await getDatabase();
  const entries = Object.entries(settingsPatch) as Array<[keyof AppSettings, AppSettings[keyof AppSettings]]>;

  for (const [key, value] of entries) {
    await database.runAsync(
      'INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value',
      [key, JSON.stringify(value)]
    );
  }
}

/** Save a recent search term and keep the history list bounded. */
export async function recordRecentSearch(term: string) {
  const trimmedTerm = term.trim();

  if (!trimmedTerm) {
    return;
  }

  const database = await getDatabase();
  const now = Date.now();

  await database.runAsync(
    'INSERT INTO recent_searches (term, used_at) VALUES (?, ?) ON CONFLICT(term) DO UPDATE SET used_at = excluded.used_at',
    [trimmedTerm, now]
  );

  await database.runAsync(
    `DELETE FROM recent_searches WHERE term NOT IN (
      SELECT term FROM recent_searches ORDER BY used_at DESC LIMIT 6
    )`
  );
}