// Generated by GitHub Copilot
import { useNavigation, NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator, NativeStackNavigationProp } from '@react-navigation/native-stack';
import * as Linking from 'expo-linking';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, View } from 'react-native';

import { ReaderScreen } from '../screens/ReaderScreen';
import { SearchScreen } from '../screens/SearchScreen';
import { EditorScreen } from '../screens/EditorScreen';
import { LibraryScreen } from '../screens/LibraryScreen';
import { useAppContext } from '../state/AppContext';
import { importDocumentFromUri } from '../storage/library';
import { useThemeController } from '../theme/ThemeProvider';
import { RootStackParamList } from '../types';

const Stack = createNativeStackNavigator<RootStackParamList>();

/** Listens for file intents (e.g. from WhatsApp) and navigates to them immediately. */
function IntentHandler() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { refreshLibrary, setLastOpenedDocumentId } = useAppContext();
  const { tokens } = useThemeController();
  const incomingUrl = Linking.useURL();
  // A ref (not state) so marking a URL as processed never retriggers this effect
  // and cancels the in-flight import.
  const processedUrlsRef = useRef<Set<string>>(new Set());
  const [isImporting, setIsImporting] = useState(false);

  useEffect(() => {
    if (!incomingUrl || processedUrlsRef.current.has(incomingUrl)) {
      return;
    }

    if (!incomingUrl.startsWith('content://') && !incomingUrl.startsWith('file://')) {
      return;
    }

    // Mark as processed immediately so a re-render never starts a duplicate import.
    processedUrlsRef.current.add(incomingUrl);
    setIsImporting(true);

    importDocumentFromUri(incomingUrl)
      .then(async (newDoc) => {
        await refreshLibrary();
        await setLastOpenedDocumentId(newDoc.id);
        navigation.navigate('Reader', { documentId: newDoc.id });
      })
      .catch((error) => {
        console.error('Failed to import from intent:', error);
        Alert.alert(
          'Could not open file',
          "This file couldn't be opened. Make sure it is a readable Markdown or text file and try again."
        );
      })
      .finally(() => {
        setIsImporting(false);
      });
  }, [incomingUrl, refreshLibrary, setLastOpenedDocumentId, navigation]);

  if (!isImporting) {
    return null;
  }

  return (
    <View style={[styles.importOverlay, { backgroundColor: tokens.background }]} pointerEvents="auto">
      <ActivityIndicator size="large" color={tokens.accent} />
      <Text style={[styles.importLabel, { color: tokens.textSecondary }]}>Opening file…</Text>
    </View>
  );
}

/** Render the app navigation stack with gesture-driven transitions and themed chrome. */
export function AppNavigator() {
  const { navigationTheme, isDark, tokens } = useThemeController();

  return (
    <>
      <StatusBar style={isDark ? 'light' : 'dark'} />
      <NavigationContainer theme={navigationTheme}>
        <IntentHandler />
        <Stack.Navigator
          initialRouteName="Library"
          screenOptions={{
            headerShadowVisible: false,
            animation: 'slide_from_right',
            headerStyle: { backgroundColor: tokens.surface },
            headerTintColor: tokens.textPrimary,
            contentStyle: { backgroundColor: tokens.background },
          }}
        >
          <Stack.Screen component={LibraryScreen} name="Library" options={{ headerShown: false }} />
          <Stack.Screen component={ReaderScreen} name="Reader" options={{ headerShown: false, fullScreenGestureEnabled: true }} />
          <Stack.Screen
            component={EditorScreen}
            name="Editor"
            options={{
              title: 'Edit Markdown',
              presentation: 'modal',
              animation: 'slide_from_bottom',
            }}
          />
          <Stack.Screen
            component={SearchScreen}
            name="Search"
            options={{
              title: 'Search',
              presentation: 'modal',
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
}

const styles = StyleSheet.create({
  importOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  importLabel: {
    fontSize: 15,
  },
});