// Generated by GitHub Copilot
import { useNavigation, NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator, NativeStackNavigationProp } from '@react-navigation/native-stack';
import * as Linking from 'expo-linking';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useState } from 'react';

import { ReaderScreen } from '../screens/ReaderScreen';
import { SearchScreen } from '../screens/SearchScreen';
import { EditorScreen } from '../screens/EditorScreen';
import { LibraryScreen } from '../screens/LibraryScreen';
import { useAppContext } from '../state/AppContext';
import { importDocumentFromUri } from '../storage/library';
import { useThemeController } from '../theme/ThemeProvider';
import { RootStackParamList } from '../types';

const Stack = createNativeStackNavigator<RootStackParamList>();

/** Listens for file intents (e.g. from WhatsApp) and navigates to them immediately. */
function IntentHandler() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { refreshLibrary, setLastOpenedDocumentId } = useAppContext();
  const incomingUrl = Linking.useURL();
  const [processedUrls, setProcessedUrls] = useState<Set<string>>(new Set());

  useEffect(() => {
    if (incomingUrl && !processedUrls.has(incomingUrl)) {
      if (incomingUrl.startsWith('content://') || incomingUrl.startsWith('file://')) {
        importDocumentFromUri(incomingUrl)
          .then(async (newDoc) => {
            setProcessedUrls((prev) => new Set(prev).add(incomingUrl));
            await refreshLibrary();
            await setLastOpenedDocumentId(newDoc.id);
            navigation.navigate('Reader', { documentId: newDoc.id });
          })
          .catch((e) => {
            console.error('Failed to import from Intent:', e);
            setProcessedUrls((prev) => new Set(prev).add(incomingUrl));
          });
      } else {
        setProcessedUrls((prev) => new Set(prev).add(incomingUrl));
      }
    }
  }, [incomingUrl, processedUrls, refreshLibrary, setLastOpenedDocumentId, navigation]);

  return null;
}

/** Render the app navigation stack with gesture-driven transitions and themed chrome. */
export function AppNavigator() {
  const { navigationTheme, isDark, tokens } = useThemeController();

  return (
    <>
      <StatusBar style={isDark ? 'light' : 'dark'} />
      <NavigationContainer theme={navigationTheme}>
        <IntentHandler />
        <Stack.Navigator
          initialRouteName="Library"
          screenOptions={{
            headerShadowVisible: false,
            animation: 'slide_from_right',
            headerStyle: { backgroundColor: tokens.surface },
            headerTintColor: tokens.textPrimary,
            contentStyle: { backgroundColor: tokens.background },
          }}
        >
          <Stack.Screen component={LibraryScreen} name="Library" options={{ headerShown: false }} />
          <Stack.Screen component={ReaderScreen} name="Reader" options={{ headerShown: false, fullScreenGestureEnabled: true }} />
          <Stack.Screen
            component={EditorScreen}
            name="Editor"
            options={{
              title: 'Edit Markdown',
              presentation: 'modal',
              animation: 'slide_from_bottom',
            }}
          />
          <Stack.Screen
            component={SearchScreen}
            name="Search"
            options={{
              title: 'Search',
              presentation: 'modal',
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
}