// Generated by GitHub Copilot
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { StatusBar } from 'expo-status-bar';
import React from 'react';

import { ReaderScreen } from '../screens/ReaderScreen';
import { SearchScreen } from '../screens/SearchScreen';
import { EditorScreen } from '../screens/EditorScreen';
import { LibraryScreen } from '../screens/LibraryScreen';
import { useThemeController } from '../theme/ThemeProvider';
import { RootStackParamList } from '../types';

const Stack = createNativeStackNavigator<RootStackParamList>();

/** Render the app navigation stack with gesture-driven transitions and themed chrome. */
export function AppNavigator() {
  const { navigationTheme, isDark, tokens } = useThemeController();

  return (
    <>
      <StatusBar style={isDark ? 'light' : 'dark'} />
      <NavigationContainer theme={navigationTheme}>
        <Stack.Navigator
          initialRouteName="Library"
          screenOptions={{
            headerShadowVisible: false,
            animation: 'slide_from_right',
            headerStyle: { backgroundColor: tokens.surface },
            headerTintColor: tokens.textPrimary,
            contentStyle: { backgroundColor: tokens.background },
          }}
        >
          <Stack.Screen component={LibraryScreen} name="Library" options={{ headerShown: false }} />
          <Stack.Screen component={ReaderScreen} name="Reader" options={{ headerShown: false, fullScreenGestureEnabled: true }} />
          <Stack.Screen
            component={EditorScreen}
            name="Editor"
            options={{
              title: 'Edit Markdown',
              presentation: 'modal',
              animation: 'slide_from_bottom',
            }}
          />
          <Stack.Screen
            component={SearchScreen}
            name="Search"
            options={{
              title: 'Search',
              presentation: 'modal',
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
}