// Generated by GitHub Copilot
export type ThemePreference = 'system' | 'light' | 'dark' | 'amoled' | 'sepia';

export type ResolvedThemeName = 'light' | 'dark' | 'amoled' | 'sepia';

export type ViewMode = 'grid' | 'list';

export interface DocumentRecord {
  id: string;
  title: string;
  fileName: string;
  localUri: string;
  content: string;
  preview: string;
  wordCount: number;
  createdAt: number;
  updatedAt: number;
  progress: number;
  lastReadOffset: number;
  favorite: boolean;
  pinned: boolean;
}

export interface AppSettings {
  themePreference: ThemePreference;
  viewMode: ViewMode;
  fontScale: number;
  lastOpenedDocumentId: string | null;
}

export interface SearchResult {
  id: string;
  title: string;
  snippet: string;
  count: number;
}

export type RootStackParamList = {
  Library: undefined;
  Reader: { documentId: string };
  Editor: { documentId: string };
  Search: undefined;
};